// Code generated by mkunion. DO NOT EDIT.
package example

import (
	"github.com/widmogrod/mkunion/f"
)

type VehicleVisitor interface {
	VisitCar(v *Car) any
	VisitPlane(v *Plane) any
	VisitBoat(v *Boat) any
}

type Vehicle interface {
	Accept(g VehicleVisitor) any
}

func (r *Car) Accept(v VehicleVisitor) any   { return v.VisitCar(r) }
func (r *Plane) Accept(v VehicleVisitor) any { return v.VisitPlane(r) }
func (r *Boat) Accept(v VehicleVisitor) any  { return v.VisitBoat(r) }

var (
	_ Vehicle = (*Car)(nil)
	_ Vehicle = (*Plane)(nil)
	_ Vehicle = (*Boat)(nil)
)

func MustMatchVehicle[TOut any](
	x Vehicle,
	f1 func(x *Car) TOut,
	f2 func(x *Plane) TOut,
	f3 func(x *Boat) TOut,
) TOut {
	return f.MustMatch3(x, f1, f2, f3)
}

func MustMatchVehicleR2[TOut1, TOut2 any](
	x Vehicle,
	f1 func(x *Car) (TOut1, TOut2),
	f2 func(x *Plane) (TOut1, TOut2),
	f3 func(x *Boat) (TOut1, TOut2),
) (TOut1, TOut2) {
	return f.MustMatch3R2(x, f1, f2, f3)
}
