// Code generated by mkunion. DO NOT EDIT.
package example

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(TreeUnionJSONShape())
}

//shape:shape
func TreeUnionJSONShape() shape.Shape {
	return &shape.StructLike{
		Name:          "TreeUnionJSON",
		PkgName:       "example",
		PkgImportName: "github.com/widmogrod/mkunion/example",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "A",
				Type: &shape.Any{},
			},
		},
		Fields: []*shape.FieldLike{
			{
				Name: "Type",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "$type",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
			{
				Name: "Branch",
				Type: &shape.RefName{
					Name:          "RawMessage",
					PkgName:       "json",
					PkgImportName: "encoding/json",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "example.Branch",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
			{
				Name: "Leaf",
				Type: &shape.RefName{
					Name:          "RawMessage",
					PkgName:       "json",
					PkgImportName: "encoding/json",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "example.Leaf",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
		},
	}
}
