// Code generated by mkunion. DO NOT EDIT.
package example

import (
	"github.com/widmogrod/mkunion/x/schema"
)

func init() {
	schema.RegisterTransformations(TreeSchemaTransformations())
	schema.RegisterRules(TreeSchemaRules())
}

func TreeSchemaTransformations() []schema.TransformFunc {
	return []schema.TransformFunc{
		schema.WrapStruct(&Branch{}, "Branch"),
		schema.WrapStruct(&Leaf{}, "Leaf"),
	}
}

func TreeSchemaRules() []schema.RuleMatcher {
	return []schema.RuleMatcher{
		schema.UnwrapStruct(&Branch{}, "Branch"),
		schema.UnwrapStruct(&Leaf{}, "Leaf"),
	}
}
