// Code generated by mkunion. DO NOT EDIT.
package testasset

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(ExplainShape())
	shape.Register(SomeDSLShape())
}

//shape:shape

func SomeDSLShape() shape.Shape {
	return &shape.UnionLike{
		Name:          "SomeDSL",
		PkgName:       "testasset",
		PkgImportName: "github.com/widmogrod/mkunion/x/shape/testasset",
		Variant: []shape.Shape{
			ExplainShape(),
		},
	}
}

func ExplainShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Explain",
		PkgName:       "testasset",
		PkgImportName: "github.com/widmogrod/mkunion/x/shape/testasset",
		Fields: []*shape.FieldLike{
			{
				Name: "Example",
				Type: &shape.RefName{
					Name:          "Example",
					PkgName:       "testasset",
					PkgImportName: "github.com/widmogrod/mkunion/x/shape/testasset",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "example",
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "SomeDSL",
			},
		},
	}
}
