// Code generated by mkunion. DO NOT EDIT.
package testasset

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(SomeDSLUnionJSONShape())
}

//shape:shape
func SomeDSLUnionJSONShape() shape.Shape {
	return &shape.StructLike{
		Name:          "SomeDSLUnionJSON",
		PkgName:       "testasset",
		PkgImportName: "github.com/widmogrod/mkunion/x/shape/testasset",
		Fields: []*shape.FieldLike{
			{
				Name: "Type",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "$type",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
			{
				Name: "Explain",
				Type: &shape.RefName{
					Name:          "RawMessage",
					PkgName:       "json",
					PkgImportName: "encoding/json",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "testasset.Explain",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
		},
	}
}
