// Code generated by mkunion. DO NOT EDIT.
package schemaless

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(KayedAggregateShape())
}

//shape:shape
func KayedAggregateShape() shape.Shape {
	return &shape.StructLike{
		Name:          "KayedAggregate",
		PkgName:       "schemaless",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "T",
				Type: &shape.Any{},
			},
			shape.TypeParam{
				Name: "R",
				Type: &shape.Any{},
			},
		},
	}
}
