//generated by mkunion
export type FindingRecords<T> = {
	RecordType?: string,
	Where?: predicate.WherePredicates,
	Sort?: SortField[],
	Limit?: number,
	After?: Cursor,
	Before?: Cursor,
}

export type SortField = {
	Field?: string,
	Descending?: boolean,
}

export type Cursor = string

export type Record<A> = {
	ID?: string,
	Type?: string,
	Data?: A,
	Version?: number,
}

export type PageResult<A> = {
	Items?: A[],
	Next?: FindingRecords<A>,
	Prev?: FindingRecords<A>,
}

export type UpdateRecords<T> = {
	UpdatingPolicy?: UpdatingPolicy,
	Saving?: {[key: string]: T},
	Deleting?: {[key: string]: T},
}

export type UpdatingPolicy = number


//eslint-disable-next-line
import * as predicate from './github_com_widmogrod_mkunion_x_storage_predicate'
