package mkunion

import (
	log "github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/widmogrod/mkunion/x/shape"
	"testing"
)

func TestDepthFirstGenerator(t *testing.T) {
	log.SetLevel(log.DebugLevel)
	inferred, err := shape.InferFromFile("example/tree_example_lit.go")
	assert.NoError(t, err)

	g := NewReducerDepthFirstGenerator(
		inferred.RetrieveUnion("Tree2"),
		NewHelper(WithPackageName("example")),
	)

	result, err := g.Generate()
	assert.NoError(t, err)
	assert.Equal(t, `// Code generated by mkunion. DO NOT EDIT.
package example

type (
	Tree2Reducer[A any] interface {
		ReduceBranch2(x *Branch2, agg A) (result A, stop bool)
		ReduceLeaf2(x *Leaf2, agg A) (result A, stop bool)
	}
)

type Tree2DepthFirstVisitor[A any] struct {
	stop   bool
	result A
	reduce Tree2Reducer[A]
}

var _ Tree2Visitor = (*Tree2DepthFirstVisitor[any])(nil)

func (d *Tree2DepthFirstVisitor[A]) VisitBranch2(v *Branch2) any {
	d.result, d.stop = d.reduce.ReduceBranch2(v, d.result)
	if d.stop {
		return nil
	}
	if _ = v.Lit.AcceptTree2(d); d.stop {
		return nil
	}
	for idx := range v.List {
		if _ = v.List[idx].AcceptTree2(d); d.stop {
			return nil
		}
	}
	for idx, _ := range v.Map {
		if _ = v.Map[idx].AcceptTree2(d); d.stop {
			return nil
		}
	}

	return nil
}

func (d *Tree2DepthFirstVisitor[A]) VisitLeaf2(v *Leaf2) any {
	d.result, d.stop = d.reduce.ReduceLeaf2(v, d.result)
	if d.stop {
		return nil
	}

	return nil
}

func ReduceTree2DepthFirst[A any](r Tree2Reducer[A], v Tree2, init A) A {
	reducer := &Tree2DepthFirstVisitor[A]{
		result: init,
		reduce: r,
	}

	_ = v.AcceptTree2(reducer)

	return reducer.result
}`, string(result))
}
