package mkunion

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestReducerBreadthFirstGenerator(t *testing.T) {
	g := NewReducerBreadthFirstGenerator(
		"Tree",
		[]string{"Branch", "Leaf"},
		map[string][]Branching{
			"Branch": {
				{Lit: PtrStr("Lit")},
				{List: PtrStr("List")},
				{Map: PtrStr("Map")},
			},
		},
		NewHelper(WithPackageName("visitor")),
	)

	result, err := g.Generate()
	assert.NoError(t, err)
	assert.Equal(t, `// Code generated by mkunion. DO NOT EDIT.
package visitor

var _ TreeVisitor = (*TreeBreadthFirstVisitor[any])(nil)

type TreeBreadthFirstVisitor[A any] struct {
	stop   bool
	result A
	reduce TreeReducer[A]

	queue         []Tree
	visited       map[Tree]bool
	shouldExecute map[Tree]bool
}

func (d *TreeBreadthFirstVisitor[A]) VisitBranch(v *Branch) any {
	d.queue = append(d.queue, v)
	d.queue = append(d.queue, v.Lit)
	for idx := range v.List {
		d.queue = append(d.queue, v.List[idx])
	}
	for idx, _ := range v.Map {
		d.queue = append(d.queue, v.Map[idx])
	}

	if d.shouldExecute[v] {
		d.shouldExecute[v] = false
		d.result, d.stop = d.reduce.ReduceBranch(v, d.result)
	} else {
		d.execute()
	}
	return nil
}

func (d *TreeBreadthFirstVisitor[A]) VisitLeaf(v *Leaf) any {
	d.queue = append(d.queue, v)

	if d.shouldExecute[v] {
		d.shouldExecute[v] = false
		d.result, d.stop = d.reduce.ReduceLeaf(v, d.result)
	} else {
		d.execute()
	}
	return nil
}

func (d *TreeBreadthFirstVisitor[A]) execute() {
	for len(d.queue) > 0 {
		if d.stop {
			return
		}

		i := d.pop()
		if d.visited[i] {
			continue
		}
		d.visited[i] = true
		d.shouldExecute[i] = true
		i.AcceptTree(d)
	}

	return
}

func (d *TreeBreadthFirstVisitor[A]) pop() Tree {
	i := d.queue[0]
	d.queue = d.queue[1:]
	return i
}

func ReduceTreeBreadthFirst[A any](r TreeReducer[A], v Tree, init A) A {
	reducer := &TreeBreadthFirstVisitor[A]{
		result:        init,
		reduce:        r,
		queue:         []Tree{v},
		visited:       make(map[Tree]bool),
		shouldExecute: make(map[Tree]bool),
	}

	_ = v.AcceptTree(reducer)

	return reducer.result
}
`, string(result))
}
