package mkunion

import (
	"bytes"
	"text/template"
)

func PtrStr(x string) *string {
	return &x
}

type typeName = string
type variantName = string

type Branching struct {
	Lit  *string
	List *string
}

type TraverseGenerator struct {
	Name        variantName
	PackageName string
	Types       []typeName
	Branches    map[typeName][]Branching
	NoHeader    bool
}

var (
	traverseTmpl = `
{{- if not .NoHeader -}}
// Code generated by mkunion. DO NOT EDIT.
package {{ .PackageName }}
{{ end }}
{{- $root := . -}}
{{- $name := .Name }}
type (
	{{ $name }}Reducer[A any] struct {
		{{- range .Types }}
		{{ . }} func(x *{{ . }}, agg A) (result A, stop bool)
		{{- end }}
	}
)

type dfs{{ $name }}[A any] struct {
	stop   bool
	result A
	reduce {{ $name }}Reducer[A]
}

var _ {{ $name }}Visitor = (*dfs{{ $name }}[any])(nil)
{{ range $i, $type := .Types }}
func (d *dfs{{ $name }}[A]) Visit{{ . }}(v *{{ . }}) any {
	d.result, d.stop = d.reduce.{{ . }}(v, d.result)
	if d.stop {
		return nil
	}
	
	{{- range (index $root.Branches $type) -}}
	{{- if .Lit}}
	if _ = v.{{ .Lit }}.Accept(d); d.stop {
		return nil
	}
	{{- else if .List }}
	for idx := range v.{{ .List }} {
		if _ = v.{{ .List }}[idx].Accept(d); d.stop {
			return nil
		}
	}
	{{- end -}}
	{{- end }}

	return nil
}
{{ end }}
func Reduce{{ $name }}[A any](r {{ $name }}Reducer[A], v {{ $name }}, init A) A {
	reducer := &dfs{{ $name }}[A]{
		result: init,
		reduce: r,
	}

	_ = v.Accept(reducer)

	return reducer.result
}
`
)

var (
	renderTraverse = template.Must(template.New("main").Parse(traverseTmpl))
)

func (t *TraverseGenerator) Generate() ([]byte, error) {
	result := &bytes.Buffer{}
	err := renderTraverse.ExecuteTemplate(result, "main", t)
	if err != nil {
		return nil, err
	}

	return result.Bytes(), nil
}
