package main

import (
	"context"
	"flag"
	"fmt"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/sashabaranov/go-openai"
	log "github.com/sirupsen/logrus"
	"github.com/widmogrod/mkunion/x/machine"
	"github.com/widmogrod/mkunion/x/schema"
	_ "github.com/widmogrod/mkunion/x/schema"
	"github.com/widmogrod/mkunion/x/shared"
	"github.com/widmogrod/mkunion/x/storage/predicate"
	"github.com/widmogrod/mkunion/x/storage/schemaless"
	"github.com/widmogrod/mkunion/x/storage/schemaless/typedful"
	"github.com/widmogrod/mkunion/x/workflow"
	_ "github.com/widmogrod/mkunion/x/workflow"
	"io"
	"net/http"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"runtime"
	"runtime/pprof"
	"syscall"
)

// --8<-- [start:ts-gen]

// this command make sure that all types that are imported will have generated typescript mapping
//go:generate go tool mkunion shape-export --language=typescript -o ./src/workflow

// this lines defines all types that should have typescript mapping generated by above command
type (
	Workflow       = workflow.Workflow
	State          = workflow.State
	Command        = workflow.Command
	Expr           = workflow.Expr
	Predicate      = workflow.Predicate
	Reshaper       = workflow.Reshaper
	Schema         = schema.Schema
	UpdateRecords  = schemaless.UpdateRecords[schemaless.Record[any]]
	FindRecords    = schemaless.FindingRecords[schemaless.Record[any]]
	PageResult     = schemaless.PageResult[schemaless.Record[any]]
	FunctionOutput = workflow.FunctionOutput
	FunctionInput  = workflow.FunctionInput
)

// --8<-- [end:ts-gen]

//go:tag mkunion:"ChatCMD"
type (
	UserMessage struct {
		Message string
	}
)

//go:tag mkunion:"ChatResult"
type (
	SystemResponse struct {
		//OrderID 	  string
		Message   string
		ToolCalls []openai.ToolCall
	}
	UserResponse struct {
		//OrderID 	  string
		Message string
	}
	ChatResponses struct {
		Responses []ChatResult
	}
)

type ListWorkflowsFn struct {
	Count    int      `desc:"total number of words in sentence"`
	Words    []string `desc:"list of words in sentence"`
	EnumTest string   `desc:"skip words" enum:"hello,world"`
}

type RefreshStates struct{}
type RefreshFlows struct{}
type GenerateImage struct {
	Width  int `desc:"width of image as int between 50 and 500"`
	Height int `desc:"height of image as int between 50 and 500"`
}

var cpuprofile = flag.String("cpuprofile", "", "write cpu profile to `file`")
var memprofile = flag.String("memprofile", "", "write memory profile to `file`")

func main() {
	flag.Parse()
	log.SetLevel(log.DebugLevel)

	stopProfiling := startProfiling(*cpuprofile, *memprofile)
	defer stopProfiling()

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	a := newApp(openai.NewClient(os.Getenv("OPENAI_API_KEY")))

	e := echo.New()
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
	}))
	a.registerRoutes(e)

	a.startBackgroundTasks(ctx)

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sigs
		log.Infof("shutting down server")
		if err := e.Shutdown(ctx); err != nil {
			log.Errorf("failed to shutdown server: %v", err)
		}
	}()

	if err := e.Start(":8080"); err != nil {
		if err == http.ErrServerClosed {
			log.Infof("server closed")
		} else {
			log.Errorf("failed to start server: %v", err)
		}
	}

	log.Infof("exiting")
}

// startProfiling preserves the original example behavior: the CPU profile
// runs until main exits; the heap profile is written once at startup.
func startProfiling(cpuprofile, memprofile string) (stop func()) {
	stop = func() {}
	if cpuprofile != "" {
		f, err := os.Create(cpuprofile)
		if err != nil {
			log.Fatal("could not create CPU profile: ", err)
		}
		if err := pprof.StartCPUProfile(f); err != nil {
			log.Fatal("could not start CPU profile: ", err)
		}
		stop = func() {
			pprof.StopCPUProfile()
			_ = f.Close() // error handling omitted for example
		}
	}

	if memprofile != "" {
		f, err := os.Create(memprofile)
		if err != nil {
			log.Fatal("could not create memory profile: ", err)
		}
		defer f.Close() // error handling omitted for example
		runtime.GC()    // get up-to-date statistics
		if err := pprof.WriteHeapProfile(f); err != nil {
			log.Fatal("could not write memory profile: ", err)
		}
	}

	return stop
}

func TypedJSONRequest[A, B any](handle func(ctx context.Context, x A) (B, error)) func(c echo.Context) error {
	return func(c echo.Context) error {
		data, err := io.ReadAll(c.Request().Body)
		if err != nil {
			log.Errorf("TypedJSONRequest: failed to read request body: %v", err)
			return err
		}

		in, err := shared.JSONUnmarshal[A](data)
		if err != nil {
			log.Errorf("TypedJSONRequest: failed to parse request body: %v", err)
			return err
		}

		out, err := handle(c.Request().Context(), in)
		if err != nil {
			return err
		}

		if _, ok := any(out).(B); !ok {
			var b B
			return fmt.Errorf("TypedJSONRequest: TypedRequest: expected %T, got %T", b, out)
		}

		result, err := shared.JSONMarshal[B](out)
		if err != nil {
			log.Errorf("TypedJSONRequest: failed to convert to json: %v", err)
			return err
		}

		return c.JSONBlob(http.StatusOK, result)
	}
}

func NewService[Dep any, CMD any, State any](
	recordType string,
	statesRepo *typedful.TypedRepoWithAggregator[State, any],
	newMachine func(state State) *machine.Machine[Dep, CMD, State],
	extractWhere func(CMD) (*predicate.WherePredicates, bool),
	extractIDFromState func(State) (string, bool),
) *Service[Dep, CMD, State] {
	return &Service[Dep, CMD, State]{
		repo:                     statesRepo,
		extractWhereFromCommandF: extractWhere,
		recordType:               recordType,
		newMachine:               newMachine,
		extractIDFromStateF:      extractIDFromState,
	}
}

type Service[Dep any, CMD any, State any] struct {
	repo                     *typedful.TypedRepoWithAggregator[State, any]
	extractWhereFromCommandF func(CMD) (*predicate.WherePredicates, bool)
	extractIDFromStateF      func(State) (string, bool)
	recordType               string
	newMachine               func(state State) *machine.Machine[Dep, CMD, State]
}

func (service *Service[Dep, CMD, State]) CreateOrUpdate(ctx context.Context, cmd CMD) (res State, err error) {
	version := uint16(0)
	recordID := ""
	where, foundAndUpdate := service.extractWhereFromCommandF(cmd)
	if foundAndUpdate {
		records, err := service.repo.FindingRecords(schemaless.FindingRecords[schemaless.Record[State]]{
			RecordType: service.recordType,
			Where:      where,
			Limit:      1,
		})
		if err != nil {
			return res, err
		}
		if len(records.Items) == 0 {
			return res, fmt.Errorf("expected at least one record")
		}

		record := records.Items[0]
		res = record.Data
		version = record.Version
		recordID = record.ID
	}

	work := service.newMachine(res)
	err = work.Handle(ctx, cmd)
	if err != nil {
		log.Errorf("failed to handle command: %v", err)
		return res, err
	}

	newState := work.State()
	if !foundAndUpdate {
		saveId, ok := service.extractIDFromStateF(newState)
		if !ok {
			return res, fmt.Errorf("expected recordID in state")
		}
		recordID = saveId
	}

	if recordID == "" {
		return res, fmt.Errorf("expected recordID in state")
	}

	_, err = service.repo.UpdateRecords(schemaless.Save(schemaless.Record[State]{
		ID:      recordID,
		Type:    service.recordType,
		Data:    newState,
		Version: version,
	}))

	if err != nil {
		return res, err
	}

	return newState, nil
}

func (service *Service[Dep, CMD, State]) StateByID(id string) (res State, err error) {
	record, err := service.repo.Get(id, service.recordType)
	if err != nil {
		err = fmt.Errorf("service.Service.StateByID(%s) err=%w", id, err)
		return
	}

	return record.Data, nil
}
