### example request
POST http://instant-answer.external.platform-services-answerbot-dev.z-dn.net/v2
Content-Type: application/json
Accept: application/json

{
  "accessKey": "7890f5c3-7147-434e-84f9-1e0351351c31",
  "prompt": "who whas napoleon bonaparte?",
  "market": "us",
  "subject": "history"
}

