// Code generated by mkunion. DO NOT EDIT.
package stream

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(PullCMDUnionJSONShape())
}

//shape:shape
func PullCMDUnionJSONShape() shape.Shape {
	return &shape.StructLike{
		Name:          "PullCMDUnionJSON",
		PkgName:       "stream",
		PkgImportName: "github.com/widmogrod/mkunion/x/stream",
		Fields: []*shape.FieldLike{
			{
				Name: "Type",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "$type",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
			{
				Name: "FromBeginning",
				Type: &shape.RefName{
					Name:          "RawMessage",
					PkgName:       "json",
					PkgImportName: "encoding/json",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "stream.FromBeginning",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
			{
				Name: "FromOffset",
				Type: &shape.RefName{
					Name:          "RawMessage",
					PkgName:       "json",
					PkgImportName: "encoding/json",
				},
				Tags: map[string]shape.Tag{
					"json": {
						Value: "stream.FromOffset",
						Options: []string{
							"omitempty",
						},
					},
				},
			},
		},
	}
}
