name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "inbox"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages, logs, or stack traces
      render: shell
      placeholder: |
        Paste any relevant error output here.
        This will be automatically formatted as code.

  - type: input
    id: version
    attributes:
      label: mkunion Version
      description: Output of `mkunion --version` or git commit hash
      placeholder: "e.g., v1.0.0 or commit abc123"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "e.g., go version go1.21.0 darwin/arm64"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Minimal code example that reproduces the issue
      render: go
      placeholder: |
        //go:tag mkunion:"Example"
        type (
            Foo struct { Value string }
            Bar struct { Count int }
        )

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How does this bug affect your work?
      options:
        - Blocking - Cannot continue development
        - High - Significant workaround required
        - Medium - Minor workaround available
        - Low - Cosmetic or minor issue
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any workaround for this issue?
      placeholder: Describe any temporary solution you've found

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have provided a minimal reproduction case
          required: true
        - label: I have included all relevant error messages
          required: true