// Code generated by mkunion. DO NOT EDIT.
package welcome

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/widmogrod/mkunion/f"
	"github.com/widmogrod/mkunion/x/shared"
	"time"
)

type ChargeErrorVisitor interface {
	VisitOutOfBudget(v *OutOfBudget) any
	VisitQuotaExceeded(v *QuotaExceeded) any
}

type ChargeError interface {
	AcceptChargeError(g ChargeErrorVisitor) any
}

var (
	_ ChargeError = (*OutOfBudget)(nil)
	_ ChargeError = (*QuotaExceeded)(nil)
)

func (r *OutOfBudget) AcceptChargeError(v ChargeErrorVisitor) any   { return v.VisitOutOfBudget(r) }
func (r *QuotaExceeded) AcceptChargeError(v ChargeErrorVisitor) any { return v.VisitQuotaExceeded(r) }

func MatchChargeErrorR3[T0, T1, T2 any](
	x ChargeError,
	f1 func(x *OutOfBudget) (T0, T1, T2),
	f2 func(x *QuotaExceeded) (T0, T1, T2),
) (T0, T1, T2) {
	switch v := x.(type) {
	case *OutOfBudget:
		return f1(v)
	case *QuotaExceeded:
		return f2(v)
	}
	var result1 T0
	var result2 T1
	var result3 T2
	return result1, result2, result3
}

func MatchChargeErrorR2[T0, T1 any](
	x ChargeError,
	f1 func(x *OutOfBudget) (T0, T1),
	f2 func(x *QuotaExceeded) (T0, T1),
) (T0, T1) {
	switch v := x.(type) {
	case *OutOfBudget:
		return f1(v)
	case *QuotaExceeded:
		return f2(v)
	}
	var result1 T0
	var result2 T1
	return result1, result2
}

func MatchChargeErrorR1[T0 any](
	x ChargeError,
	f1 func(x *OutOfBudget) T0,
	f2 func(x *QuotaExceeded) T0,
) T0 {
	switch v := x.(type) {
	case *OutOfBudget:
		return f1(v)
	case *QuotaExceeded:
		return f2(v)
	}
	var result1 T0
	return result1
}

func MatchChargeErrorR0(
	x ChargeError,
	f1 func(x *OutOfBudget),
	f2 func(x *QuotaExceeded),
) {
	switch v := x.(type) {
	case *OutOfBudget:
		f1(v)
	case *QuotaExceeded:
		f2(v)
	}
}
func init() {
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.ChargeError", ChargeErrorFromJSON, ChargeErrorToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.OutOfBudget", OutOfBudgetFromJSON, OutOfBudgetToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.QuotaExceeded", QuotaExceededFromJSON, QuotaExceededToJSON)
}

type ChargeErrorUnionJSON struct {
	Type          string          `json:"$type,omitempty"`
	OutOfBudget   json.RawMessage `json:"welcome.OutOfBudget,omitempty"`
	QuotaExceeded json.RawMessage `json:"welcome.QuotaExceeded,omitempty"`
}

func ChargeErrorFromJSON(x []byte) (ChargeError, error) {
	if x == nil || len(x) == 0 {
		return nil, nil
	}
	if string(x[:4]) == "null" {
		return nil, nil
	}
	var data ChargeErrorUnionJSON
	err := json.Unmarshal(x, &data)
	if err != nil {
		return nil, fmt.Errorf("welcome.ChargeErrorFromJSON: %w", err)
	}

	switch data.Type {
	case "welcome.OutOfBudget":
		return OutOfBudgetFromJSON(data.OutOfBudget)
	case "welcome.QuotaExceeded":
		return QuotaExceededFromJSON(data.QuotaExceeded)
	}

	if data.OutOfBudget != nil {
		return OutOfBudgetFromJSON(data.OutOfBudget)
	} else if data.QuotaExceeded != nil {
		return QuotaExceededFromJSON(data.QuotaExceeded)
	}
	return nil, fmt.Errorf("welcome.ChargeErrorFromJSON: unknown type: %s", data.Type)
}

func ChargeErrorToJSON(x ChargeError) ([]byte, error) {
	if x == nil {
		return []byte(`null`), nil
	}
	return MatchChargeErrorR2(
		x,
		func(y *OutOfBudget) ([]byte, error) {
			body, err := OutOfBudgetToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:        "welcome.OutOfBudget",
				OutOfBudget: body,
			})
		},
		func(y *QuotaExceeded) ([]byte, error) {
			body, err := QuotaExceededToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:          "welcome.QuotaExceeded",
				QuotaExceeded: body,
			})
		},
	)
}

func OutOfBudgetFromJSON(x []byte) (*OutOfBudget, error) {
	result := new(OutOfBudget)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.OutOfBudgetFromJSON: %w", err)
	}
	return result, nil
}

func OutOfBudgetToJSON(x *OutOfBudget) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*OutOfBudget)(nil)
	_ json.Marshaler   = (*OutOfBudget)(nil)
)

func (r *OutOfBudget) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONOutOfBudget(*r)
}
func (r *OutOfBudget) _marshalJSONOutOfBudget(x OutOfBudget) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldMissing []byte
	fieldMissing, err = r._marshalJSONint(x.Missing)
	if err != nil {
		return nil, fmt.Errorf("welcome: OutOfBudget._marshalJSONOutOfBudget: field name Missing; %w", err)
	}
	if len(fieldMissing) == 0 {
		fieldMissing = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Missing\":")
	buf.Write(fieldMissing)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *OutOfBudget) _marshalJSONint(x int) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: OutOfBudget._marshalJSONint:; %w", err)
	}
	return result, nil
}
func (r *OutOfBudget) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONOutOfBudget(data)
	if err != nil {
		return fmt.Errorf("welcome: OutOfBudget.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *OutOfBudget) _unmarshalJSONOutOfBudget(data []byte) (OutOfBudget, error) {
	result := OutOfBudget{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: OutOfBudget._unmarshalJSONOutOfBudget: native struct unwrap; %w", err)
	}
	if fieldMissing, ok := partial["Missing"]; ok {
		result.Missing, err = r._unmarshalJSONint(fieldMissing)
		if err != nil {
			return result, fmt.Errorf("welcome: OutOfBudget._unmarshalJSONOutOfBudget: field Missing; %w", err)
		}
	}
	return result, nil
}
func (r *OutOfBudget) _unmarshalJSONint(data []byte) (int, error) {
	var result int
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: OutOfBudget._unmarshalJSONint: native primitive unwrap; %w", err)
	}
	return result, nil
}

func QuotaExceededFromJSON(x []byte) (*QuotaExceeded, error) {
	result := new(QuotaExceeded)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.QuotaExceededFromJSON: %w", err)
	}
	return result, nil
}

func QuotaExceededToJSON(x *QuotaExceeded) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*QuotaExceeded)(nil)
	_ json.Marshaler   = (*QuotaExceeded)(nil)
)

func (r *QuotaExceeded) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONQuotaExceeded(*r)
}
func (r *QuotaExceeded) _marshalJSONQuotaExceeded(x QuotaExceeded) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldResetAt []byte
	fieldResetAt, err = r._marshalJSONtime_Time(x.ResetAt)
	if err != nil {
		return nil, fmt.Errorf("welcome: QuotaExceeded._marshalJSONQuotaExceeded: field name ResetAt; %w", err)
	}
	if len(fieldResetAt) == 0 {
		fieldResetAt = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"ResetAt\":")
	buf.Write(fieldResetAt)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *QuotaExceeded) _marshalJSONtime_Time(x time.Time) ([]byte, error) {
	result, err := shared.JSONMarshal[time.Time](x)
	if err != nil {
		return nil, fmt.Errorf("welcome: QuotaExceeded._marshalJSONtime_Time:; %w", err)
	}
	return result, nil
}
func (r *QuotaExceeded) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONQuotaExceeded(data)
	if err != nil {
		return fmt.Errorf("welcome: QuotaExceeded.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *QuotaExceeded) _unmarshalJSONQuotaExceeded(data []byte) (QuotaExceeded, error) {
	result := QuotaExceeded{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: QuotaExceeded._unmarshalJSONQuotaExceeded: native struct unwrap; %w", err)
	}
	if fieldResetAt, ok := partial["ResetAt"]; ok {
		result.ResetAt, err = r._unmarshalJSONtime_Time(fieldResetAt)
		if err != nil {
			return result, fmt.Errorf("welcome: QuotaExceeded._unmarshalJSONQuotaExceeded: field ResetAt; %w", err)
		}
	}
	return result, nil
}
func (r *QuotaExceeded) _unmarshalJSONtime_Time(data []byte) (time.Time, error) {
	result, err := shared.JSONUnmarshal[time.Time](data)
	if err != nil {
		return result, fmt.Errorf("welcome: QuotaExceeded._unmarshalJSONtime_Time: native ref unwrap; %w", err)
	}
	return result, nil
}

type MyEffVisitor interface {
	VisitLog(v *Log) any
	VisitNow(v *Now) any
	VisitReadFile(v *ReadFile) any
	VisitRandom(v *Random) any
	VisitSend(v *Send) any
	VisitCharge(v *Charge) any
}

type MyEff interface {
	AcceptMyEff(g MyEffVisitor) any
}

var (
	_ MyEff = (*Log)(nil)
	_ MyEff = (*Now)(nil)
	_ MyEff = (*ReadFile)(nil)
	_ MyEff = (*Random)(nil)
	_ MyEff = (*Send)(nil)
	_ MyEff = (*Charge)(nil)
)

func (r *Log) AcceptMyEff(v MyEffVisitor) any      { return v.VisitLog(r) }
func (r *Now) AcceptMyEff(v MyEffVisitor) any      { return v.VisitNow(r) }
func (r *ReadFile) AcceptMyEff(v MyEffVisitor) any { return v.VisitReadFile(r) }
func (r *Random) AcceptMyEff(v MyEffVisitor) any   { return v.VisitRandom(r) }
func (r *Send) AcceptMyEff(v MyEffVisitor) any     { return v.VisitSend(r) }
func (r *Charge) AcceptMyEff(v MyEffVisitor) any   { return v.VisitCharge(r) }

func MatchMyEffR3[T0, T1, T2 any](
	x MyEff,
	f1 func(x *Log) (T0, T1, T2),
	f2 func(x *Now) (T0, T1, T2),
	f3 func(x *ReadFile) (T0, T1, T2),
	f4 func(x *Random) (T0, T1, T2),
	f5 func(x *Send) (T0, T1, T2),
	f6 func(x *Charge) (T0, T1, T2),
) (T0, T1, T2) {
	switch v := x.(type) {
	case *Log:
		return f1(v)
	case *Now:
		return f2(v)
	case *ReadFile:
		return f3(v)
	case *Random:
		return f4(v)
	case *Send:
		return f5(v)
	case *Charge:
		return f6(v)
	}
	var result1 T0
	var result2 T1
	var result3 T2
	return result1, result2, result3
}

func MatchMyEffR2[T0, T1 any](
	x MyEff,
	f1 func(x *Log) (T0, T1),
	f2 func(x *Now) (T0, T1),
	f3 func(x *ReadFile) (T0, T1),
	f4 func(x *Random) (T0, T1),
	f5 func(x *Send) (T0, T1),
	f6 func(x *Charge) (T0, T1),
) (T0, T1) {
	switch v := x.(type) {
	case *Log:
		return f1(v)
	case *Now:
		return f2(v)
	case *ReadFile:
		return f3(v)
	case *Random:
		return f4(v)
	case *Send:
		return f5(v)
	case *Charge:
		return f6(v)
	}
	var result1 T0
	var result2 T1
	return result1, result2
}

func MatchMyEffR1[T0 any](
	x MyEff,
	f1 func(x *Log) T0,
	f2 func(x *Now) T0,
	f3 func(x *ReadFile) T0,
	f4 func(x *Random) T0,
	f5 func(x *Send) T0,
	f6 func(x *Charge) T0,
) T0 {
	switch v := x.(type) {
	case *Log:
		return f1(v)
	case *Now:
		return f2(v)
	case *ReadFile:
		return f3(v)
	case *Random:
		return f4(v)
	case *Send:
		return f5(v)
	case *Charge:
		return f6(v)
	}
	var result1 T0
	return result1
}

func MatchMyEffR0(
	x MyEff,
	f1 func(x *Log),
	f2 func(x *Now),
	f3 func(x *ReadFile),
	f4 func(x *Random),
	f5 func(x *Send),
	f6 func(x *Charge),
) {
	switch v := x.(type) {
	case *Log:
		f1(v)
	case *Now:
		f2(v)
	case *ReadFile:
		f3(v)
	case *Random:
		f4(v)
	case *Send:
		f5(v)
	case *Charge:
		f6(v)
	}
}

// MyEffHandler answers every MyEff with the type it declares in f.Returns.
// Adding a variant to MyEff breaks every MyEffHandler at compile time.
type MyEffHandler interface {
	HandleLog(ctx context.Context, op *Log) (Unit, error)
	HandleNow(ctx context.Context, op *Now) (time.Time, error)
	HandleReadFile(ctx context.Context, op *ReadFile) ([]uint8, error)
	HandleRandom(ctx context.Context, op *Random) (int, error)
	HandleSend(ctx context.Context, op *Send) (string, error)
	HandleCharge(ctx context.Context, op *Charge) (f.Result[Receipt, ChargeError], error)
}

// MyEffOf is a MyEff that answers with R.
type MyEffOf[R any] interface {
	MyEff
	HandleMyEff(ctx context.Context, h MyEffHandler) (R, error)
}

var (
	_ MyEffOf[Unit]                           = (*Log)(nil)
	_ MyEffOf[time.Time]                      = (*Now)(nil)
	_ MyEffOf[[]uint8]                        = (*ReadFile)(nil)
	_ MyEffOf[int]                            = (*Random)(nil)
	_ MyEffOf[string]                         = (*Send)(nil)
	_ MyEffOf[f.Result[Receipt, ChargeError]] = (*Charge)(nil)
)

func (r *Log) HandleMyEff(ctx context.Context, h MyEffHandler) (Unit, error) {
	return h.HandleLog(ctx, r)
}

func (r *Now) HandleMyEff(ctx context.Context, h MyEffHandler) (time.Time, error) {
	return h.HandleNow(ctx, r)
}

func (r *ReadFile) HandleMyEff(ctx context.Context, h MyEffHandler) ([]uint8, error) {
	return h.HandleReadFile(ctx, r)
}

func (r *Random) HandleMyEff(ctx context.Context, h MyEffHandler) (int, error) {
	return h.HandleRandom(ctx, r)
}

func (r *Send) HandleMyEff(ctx context.Context, h MyEffHandler) (string, error) {
	return h.HandleSend(ctx, r)
}

func (r *Charge) HandleMyEff(ctx context.Context, h MyEffHandler) (f.Result[Receipt, ChargeError], error) {
	return h.HandleCharge(ctx, r)
}

// MyEffHandlerFunc adapts a typed MyEffHandler to a plain function over the union.
// The answer is the type the variant declares; only its static type is lost.
func MyEffHandlerFunc(h MyEffHandler) func(ctx context.Context, op MyEff) (any, error) {
	return func(ctx context.Context, op MyEff) (any, error) {
		return MatchMyEffR2(op,
			func(x *Log) (any, error) { return x.HandleMyEff(ctx, h) },
			func(x *Now) (any, error) { return x.HandleMyEff(ctx, h) },
			func(x *ReadFile) (any, error) { return x.HandleMyEff(ctx, h) },
			func(x *Random) (any, error) { return x.HandleMyEff(ctx, h) },
			func(x *Send) (any, error) { return x.HandleMyEff(ctx, h) },
			func(x *Charge) (any, error) { return x.HandleMyEff(ctx, h) },
		)
	}
}

// MyEffDefaults answers every MyEff with the zero value of its declared type.
// Embed it in a handler and override only the methods you care about.
type MyEffDefaults struct{}

var _ MyEffHandler = MyEffDefaults{}

func (MyEffDefaults) HandleLog(context.Context, *Log) (Unit, error) {
	var zero Unit
	return zero, nil
}

func (MyEffDefaults) HandleNow(context.Context, *Now) (time.Time, error) {
	var zero time.Time
	return zero, nil
}

func (MyEffDefaults) HandleReadFile(context.Context, *ReadFile) ([]uint8, error) {
	var zero []uint8
	return zero, nil
}

func (MyEffDefaults) HandleRandom(context.Context, *Random) (int, error) {
	var zero int
	return zero, nil
}

func (MyEffDefaults) HandleSend(context.Context, *Send) (string, error) {
	var zero string
	return zero, nil
}

func (MyEffDefaults) HandleCharge(context.Context, *Charge) (f.Result[Receipt, ChargeError], error) {
	var zero f.Result[Receipt, ChargeError]
	return zero, nil
}

// MyEffFuncs is a MyEffHandler made of functions, one per operation, for handlers
// written inline. A nil function answers with the zero value of its declared type.
type MyEffFuncs struct {
	Log      func(ctx context.Context, op *Log) (Unit, error)
	Now      func(ctx context.Context, op *Now) (time.Time, error)
	ReadFile func(ctx context.Context, op *ReadFile) ([]uint8, error)
	Random   func(ctx context.Context, op *Random) (int, error)
	Send     func(ctx context.Context, op *Send) (string, error)
	Charge   func(ctx context.Context, op *Charge) (f.Result[Receipt, ChargeError], error)
}

var _ MyEffHandler = MyEffFuncs{}

func (fs MyEffFuncs) HandleLog(ctx context.Context, op *Log) (Unit, error) {
	if fs.Log == nil {
		var zero Unit
		return zero, nil
	}
	return fs.Log(ctx, op)
}

func (fs MyEffFuncs) HandleNow(ctx context.Context, op *Now) (time.Time, error) {
	if fs.Now == nil {
		var zero time.Time
		return zero, nil
	}
	return fs.Now(ctx, op)
}

func (fs MyEffFuncs) HandleReadFile(ctx context.Context, op *ReadFile) ([]uint8, error) {
	if fs.ReadFile == nil {
		var zero []uint8
		return zero, nil
	}
	return fs.ReadFile(ctx, op)
}

func (fs MyEffFuncs) HandleRandom(ctx context.Context, op *Random) (int, error) {
	if fs.Random == nil {
		var zero int
		return zero, nil
	}
	return fs.Random(ctx, op)
}

func (fs MyEffFuncs) HandleSend(ctx context.Context, op *Send) (string, error) {
	if fs.Send == nil {
		var zero string
		return zero, nil
	}
	return fs.Send(ctx, op)
}

func (fs MyEffFuncs) HandleCharge(ctx context.Context, op *Charge) (f.Result[Receipt, ChargeError], error) {
	if fs.Charge == nil {
		var zero f.Result[Receipt, ChargeError]
		return zero, nil
	}
	return fs.Charge(ctx, op)
}

func init() {
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.Charge", ChargeFromJSON, ChargeToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.Log", LogFromJSON, LogToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.MyEff", MyEffFromJSON, MyEffToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.Now", NowFromJSON, NowToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.Random", RandomFromJSON, RandomToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.ReadFile", ReadFileFromJSON, ReadFileToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/welcome.Send", SendFromJSON, SendToJSON)
}

type MyEffUnionJSON struct {
	Type     string          `json:"$type,omitempty"`
	Log      json.RawMessage `json:"welcome.Log,omitempty"`
	Now      json.RawMessage `json:"welcome.Now,omitempty"`
	ReadFile json.RawMessage `json:"welcome.ReadFile,omitempty"`
	Random   json.RawMessage `json:"welcome.Random,omitempty"`
	Send     json.RawMessage `json:"welcome.Send,omitempty"`
	Charge   json.RawMessage `json:"welcome.Charge,omitempty"`
}

func MyEffFromJSON(x []byte) (MyEff, error) {
	if x == nil || len(x) == 0 {
		return nil, nil
	}
	if string(x[:4]) == "null" {
		return nil, nil
	}
	var data MyEffUnionJSON
	err := json.Unmarshal(x, &data)
	if err != nil {
		return nil, fmt.Errorf("welcome.MyEffFromJSON: %w", err)
	}

	switch data.Type {
	case "welcome.Log":
		return LogFromJSON(data.Log)
	case "welcome.Now":
		return NowFromJSON(data.Now)
	case "welcome.ReadFile":
		return ReadFileFromJSON(data.ReadFile)
	case "welcome.Random":
		return RandomFromJSON(data.Random)
	case "welcome.Send":
		return SendFromJSON(data.Send)
	case "welcome.Charge":
		return ChargeFromJSON(data.Charge)
	}

	if data.Log != nil {
		return LogFromJSON(data.Log)
	} else if data.Now != nil {
		return NowFromJSON(data.Now)
	} else if data.ReadFile != nil {
		return ReadFileFromJSON(data.ReadFile)
	} else if data.Random != nil {
		return RandomFromJSON(data.Random)
	} else if data.Send != nil {
		return SendFromJSON(data.Send)
	} else if data.Charge != nil {
		return ChargeFromJSON(data.Charge)
	}
	return nil, fmt.Errorf("welcome.MyEffFromJSON: unknown type: %s", data.Type)
}

func MyEffToJSON(x MyEff) ([]byte, error) {
	if x == nil {
		return []byte(`null`), nil
	}
	return MatchMyEffR2(
		x,
		func(y *Log) ([]byte, error) {
			body, err := LogToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type: "welcome.Log",
				Log:  body,
			})
		},
		func(y *Now) ([]byte, error) {
			body, err := NowToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type: "welcome.Now",
				Now:  body,
			})
		},
		func(y *ReadFile) ([]byte, error) {
			body, err := ReadFileToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type:     "welcome.ReadFile",
				ReadFile: body,
			})
		},
		func(y *Random) ([]byte, error) {
			body, err := RandomToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type:   "welcome.Random",
				Random: body,
			})
		},
		func(y *Send) ([]byte, error) {
			body, err := SendToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type: "welcome.Send",
				Send: body,
			})
		},
		func(y *Charge) ([]byte, error) {
			body, err := ChargeToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("welcome.MyEffToJSON: %w", err)
			}
			return json.Marshal(MyEffUnionJSON{
				Type:   "welcome.Charge",
				Charge: body,
			})
		},
	)
}

func LogFromJSON(x []byte) (*Log, error) {
	result := new(Log)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.LogFromJSON: %w", err)
	}
	return result, nil
}

func LogToJSON(x *Log) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Log)(nil)
	_ json.Marshaler   = (*Log)(nil)
)

func (r *Log) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONLog(*r)
}
func (r *Log) _marshalJSONLog(x Log) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldMsg []byte
	fieldMsg, err = r._marshalJSONstring(x.Msg)
	if err != nil {
		return nil, fmt.Errorf("welcome: Log._marshalJSONLog: field name Msg; %w", err)
	}
	if len(fieldMsg) == 0 {
		fieldMsg = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Msg\":")
	buf.Write(fieldMsg)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *Log) _marshalJSONstring(x string) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: Log._marshalJSONstring:; %w", err)
	}
	return result, nil
}
func (r *Log) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONLog(data)
	if err != nil {
		return fmt.Errorf("welcome: Log.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Log) _unmarshalJSONLog(data []byte) (Log, error) {
	result := Log{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: Log._unmarshalJSONLog: native struct unwrap; %w", err)
	}
	if fieldMsg, ok := partial["Msg"]; ok {
		result.Msg, err = r._unmarshalJSONstring(fieldMsg)
		if err != nil {
			return result, fmt.Errorf("welcome: Log._unmarshalJSONLog: field Msg; %w", err)
		}
	}
	return result, nil
}
func (r *Log) _unmarshalJSONstring(data []byte) (string, error) {
	var result string
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: Log._unmarshalJSONstring: native primitive unwrap; %w", err)
	}
	return result, nil
}

func NowFromJSON(x []byte) (*Now, error) {
	result := new(Now)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.NowFromJSON: %w", err)
	}
	return result, nil
}

func NowToJSON(x *Now) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Now)(nil)
	_ json.Marshaler   = (*Now)(nil)
)

func (r *Now) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONNow(*r)
}
func (r *Now) _marshalJSONNow(x Now) ([]byte, error) {
	return []byte("{}"), nil
}
func (r *Now) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONNow(data)
	if err != nil {
		return fmt.Errorf("welcome: Now.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Now) _unmarshalJSONNow(data []byte) (Now, error) {
	result := Now{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: Now._unmarshalJSONNow: native struct unwrap; %w", err)
	}
	return result, nil
}

func ReadFileFromJSON(x []byte) (*ReadFile, error) {
	result := new(ReadFile)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.ReadFileFromJSON: %w", err)
	}
	return result, nil
}

func ReadFileToJSON(x *ReadFile) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*ReadFile)(nil)
	_ json.Marshaler   = (*ReadFile)(nil)
)

func (r *ReadFile) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONReadFile(*r)
}
func (r *ReadFile) _marshalJSONReadFile(x ReadFile) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldPath []byte
	fieldPath, err = r._marshalJSONstring(x.Path)
	if err != nil {
		return nil, fmt.Errorf("welcome: ReadFile._marshalJSONReadFile: field name Path; %w", err)
	}
	if len(fieldPath) == 0 {
		fieldPath = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Path\":")
	buf.Write(fieldPath)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *ReadFile) _marshalJSONstring(x string) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: ReadFile._marshalJSONstring:; %w", err)
	}
	return result, nil
}
func (r *ReadFile) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONReadFile(data)
	if err != nil {
		return fmt.Errorf("welcome: ReadFile.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *ReadFile) _unmarshalJSONReadFile(data []byte) (ReadFile, error) {
	result := ReadFile{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: ReadFile._unmarshalJSONReadFile: native struct unwrap; %w", err)
	}
	if fieldPath, ok := partial["Path"]; ok {
		result.Path, err = r._unmarshalJSONstring(fieldPath)
		if err != nil {
			return result, fmt.Errorf("welcome: ReadFile._unmarshalJSONReadFile: field Path; %w", err)
		}
	}
	return result, nil
}
func (r *ReadFile) _unmarshalJSONstring(data []byte) (string, error) {
	var result string
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: ReadFile._unmarshalJSONstring: native primitive unwrap; %w", err)
	}
	return result, nil
}

func RandomFromJSON(x []byte) (*Random, error) {
	result := new(Random)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.RandomFromJSON: %w", err)
	}
	return result, nil
}

func RandomToJSON(x *Random) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Random)(nil)
	_ json.Marshaler   = (*Random)(nil)
)

func (r *Random) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONRandom(*r)
}
func (r *Random) _marshalJSONRandom(x Random) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldMax []byte
	fieldMax, err = r._marshalJSONint(x.Max)
	if err != nil {
		return nil, fmt.Errorf("welcome: Random._marshalJSONRandom: field name Max; %w", err)
	}
	if len(fieldMax) == 0 {
		fieldMax = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Max\":")
	buf.Write(fieldMax)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *Random) _marshalJSONint(x int) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: Random._marshalJSONint:; %w", err)
	}
	return result, nil
}
func (r *Random) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONRandom(data)
	if err != nil {
		return fmt.Errorf("welcome: Random.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Random) _unmarshalJSONRandom(data []byte) (Random, error) {
	result := Random{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: Random._unmarshalJSONRandom: native struct unwrap; %w", err)
	}
	if fieldMax, ok := partial["Max"]; ok {
		result.Max, err = r._unmarshalJSONint(fieldMax)
		if err != nil {
			return result, fmt.Errorf("welcome: Random._unmarshalJSONRandom: field Max; %w", err)
		}
	}
	return result, nil
}
func (r *Random) _unmarshalJSONint(data []byte) (int, error) {
	var result int
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: Random._unmarshalJSONint: native primitive unwrap; %w", err)
	}
	return result, nil
}

func SendFromJSON(x []byte) (*Send, error) {
	result := new(Send)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.SendFromJSON: %w", err)
	}
	return result, nil
}

func SendToJSON(x *Send) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Send)(nil)
	_ json.Marshaler   = (*Send)(nil)
)

func (r *Send) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONSend(*r)
}
func (r *Send) _marshalJSONSend(x Send) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldTo []byte
	fieldTo, err = r._marshalJSONstring(x.To)
	if err != nil {
		return nil, fmt.Errorf("welcome: Send._marshalJSONSend: field name To; %w", err)
	}
	if len(fieldTo) == 0 {
		fieldTo = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"To\":")
	buf.Write(fieldTo)
	var fieldMsg []byte
	fieldMsg, err = r._marshalJSONstring(x.Msg)
	if err != nil {
		return nil, fmt.Errorf("welcome: Send._marshalJSONSend: field name Msg; %w", err)
	}
	if len(fieldMsg) == 0 {
		fieldMsg = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Msg\":")
	buf.Write(fieldMsg)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *Send) _marshalJSONstring(x string) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: Send._marshalJSONstring:; %w", err)
	}
	return result, nil
}
func (r *Send) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONSend(data)
	if err != nil {
		return fmt.Errorf("welcome: Send.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Send) _unmarshalJSONSend(data []byte) (Send, error) {
	result := Send{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: Send._unmarshalJSONSend: native struct unwrap; %w", err)
	}
	if fieldTo, ok := partial["To"]; ok {
		result.To, err = r._unmarshalJSONstring(fieldTo)
		if err != nil {
			return result, fmt.Errorf("welcome: Send._unmarshalJSONSend: field To; %w", err)
		}
	}
	if fieldMsg, ok := partial["Msg"]; ok {
		result.Msg, err = r._unmarshalJSONstring(fieldMsg)
		if err != nil {
			return result, fmt.Errorf("welcome: Send._unmarshalJSONSend: field Msg; %w", err)
		}
	}
	return result, nil
}
func (r *Send) _unmarshalJSONstring(data []byte) (string, error) {
	var result string
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: Send._unmarshalJSONstring: native primitive unwrap; %w", err)
	}
	return result, nil
}

func ChargeFromJSON(x []byte) (*Charge, error) {
	result := new(Charge)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("welcome.ChargeFromJSON: %w", err)
	}
	return result, nil
}

func ChargeToJSON(x *Charge) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Charge)(nil)
	_ json.Marshaler   = (*Charge)(nil)
)

func (r *Charge) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONCharge(*r)
}
func (r *Charge) _marshalJSONCharge(x Charge) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldAmount []byte
	fieldAmount, err = r._marshalJSONint(x.Amount)
	if err != nil {
		return nil, fmt.Errorf("welcome: Charge._marshalJSONCharge: field name Amount; %w", err)
	}
	if len(fieldAmount) == 0 {
		fieldAmount = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Amount\":")
	buf.Write(fieldAmount)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *Charge) _marshalJSONint(x int) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("welcome: Charge._marshalJSONint:; %w", err)
	}
	return result, nil
}
func (r *Charge) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONCharge(data)
	if err != nil {
		return fmt.Errorf("welcome: Charge.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Charge) _unmarshalJSONCharge(data []byte) (Charge, error) {
	result := Charge{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("welcome: Charge._unmarshalJSONCharge: native struct unwrap; %w", err)
	}
	if fieldAmount, ok := partial["Amount"]; ok {
		result.Amount, err = r._unmarshalJSONint(fieldAmount)
		if err != nil {
			return result, fmt.Errorf("welcome: Charge._unmarshalJSONCharge: field Amount; %w", err)
		}
	}
	return result, nil
}
func (r *Charge) _unmarshalJSONint(data []byte) (int, error) {
	var result int
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("welcome: Charge._unmarshalJSONint: native primitive unwrap; %w", err)
	}
	return result, nil
}
