// Code generated by mkunion. DO NOT EDIT.
package welcome

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(clockOnlyShape())
}

//shape:shape
func clockOnlyShape() shape.Shape {
	return &shape.StructLike{
		Name:          "clockOnly",
		PkgName:       "welcome",
		PkgImportName: "github.com/widmogrod/mkunion/example/welcome",
		Fields: []*shape.FieldLike{
			{
				Name: "Defaults",
				Type: &shape.RefName{
					Name:          "Defaults",
					PkgName:       "welcome",
					PkgImportName: "github.com/widmogrod/mkunion/example/welcome",
				},
			},
		},
	}
}
