// Code generated by mkunion. DO NOT EDIT.
package welcome

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(EnvShape())
	shape.Register(abortShape())
	shape.Register(procStateShape())
}

//shape:shape
func EnvShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Env",
		PkgName:       "welcome",
		PkgImportName: "github.com/widmogrod/mkunion/example/welcome",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "Op",
				Type: &shape.Any{},
			},
		},
	}
}

//shape:shape
func abortShape() shape.Shape {
	return &shape.StructLike{
		Name:          "abort",
		PkgName:       "welcome",
		PkgImportName: "github.com/widmogrod/mkunion/example/welcome",
	}
}

//shape:shape
func procStateShape() shape.Shape {
	return &shape.StructLike{
		Name:          "procState",
		PkgName:       "welcome",
		PkgImportName: "github.com/widmogrod/mkunion/example/welcome",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "Op",
				Type: &shape.Any{},
			},
			shape.TypeParam{
				Name: "A",
				Type: &shape.Any{},
			},
		},
	}
}
