// Code generated by mkunion. DO NOT EDIT.
package clock

import (
	"github.com/widmogrod/mkunion/x/effect"
	"github.com/widmogrod/mkunion/x/shared"
	"time"
)

func init() {
	shared.TypeRegistryStore[EffectOf[effect.Unit]]("github.com/widmogrod/mkunion/example/compose/clock.EffectOf[github.com/widmogrod/mkunion/x/effect.Unit]")
	shared.TypeRegistryStore[EffectOf[time.Time]]("github.com/widmogrod/mkunion/example/compose/clock.EffectOf[time.Time]")
	shared.TypeRegistryStore[Now]("github.com/widmogrod/mkunion/example/compose/clock.Now")
	shared.TypeRegistryStore[Sleep]("github.com/widmogrod/mkunion/example/compose/clock.Sleep")
	shared.TypeRegistryStore[effect.Bind[Effect, effect.Unit]]("github.com/widmogrod/mkunion/x/effect.Bind[github.com/widmogrod/mkunion/example/compose/clock.Effect,github.com/widmogrod/mkunion/x/effect.Unit]")
	shared.TypeRegistryStore[effect.Eff[Effect, effect.Unit]]("github.com/widmogrod/mkunion/x/effect.Eff[github.com/widmogrod/mkunion/example/compose/clock.Effect,github.com/widmogrod/mkunion/x/effect.Unit]")
	shared.TypeRegistryStore[effect.Fail[Effect, effect.Unit]]("github.com/widmogrod/mkunion/x/effect.Fail[github.com/widmogrod/mkunion/example/compose/clock.Effect,github.com/widmogrod/mkunion/x/effect.Unit]")
	shared.TypeRegistryStore[effect.Pure[Effect, effect.Unit]]("github.com/widmogrod/mkunion/x/effect.Pure[github.com/widmogrod/mkunion/example/compose/clock.Effect,github.com/widmogrod/mkunion/x/effect.Unit]")
	shared.TypeRegistryStore[effect.Suspend[Effect, effect.Unit]]("github.com/widmogrod/mkunion/x/effect.Suspend[github.com/widmogrod/mkunion/example/compose/clock.Effect,github.com/widmogrod/mkunion/x/effect.Unit]")
}
