stateDiagram
	[*] --> "*workflow.Done": "*workflow.Run"
	[*] --> "*workflow.Error": "*workflow.Run"
 %% error=fauked to find workflow hello_world_flow_non_existing: flow hello_world_flow_non_existing not found 
 %% error=already started 
 %% error=already started 
