stateDiagram
	[*] --> "*workflow.Done": "*workflow.Run"
	[*] --> "*workflow.Await": "*workflow.Run"
	"*workflow.Await" --> "*workflow.Done": "*workflow.Callback"
 %% error=callback not match 
	[*] --> "*workflow.Error": "*workflow.Run"
 %% error=failed to find workflow hello_world_flow_non_existing: flow hello_world_flow_non_existing not found 
 %% error=invalid state transition 
 %% error=already started 
 %% error=already started 
 %% error=invalid state transition 
 %% error=already started 
 %% error=invalid state transition 
