// Code generated by mkunion. DO NOT EDIT.
package state

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(DependencyMockShape())
}

//shape:shape
func DependencyMockShape() shape.Shape {
	return &shape.StructLike{
		Name:          "DependencyMock",
		PkgName:       "state",
		PkgImportName: "github.com/widmogrod/mkunion/example/state",
		Fields: []*shape.FieldLike{
			{
				Name: "PaymentChargeFunc",
				Type: &shape.Any{},
			},
			{
				Name: "TimeNowFunc",
				Type: &shape.Any{},
			},
			{
				Name: "WarehouseRemoveStockFunc",
				Type: &shape.Any{},
			},
			{
				Name: "PaymentCharge",
				Type: &shape.ListLike{
					Element: &shape.Any{},
				},
			},
			{
				Name: "TimeNow",
				Type: &shape.ListLike{
					Element: &shape.Any{},
				},
			},
			{
				Name: "WarehouseRemoveStock",
				Type: &shape.ListLike{
					Element: &shape.Any{},
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Price",
				Type: &shape.RefName{
					Name:          "Price",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Quantity",
				Type: &shape.RefName{
					Name:          "Quantity",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Price",
				Type: &shape.RefName{
					Name:          "Price",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Price",
				Type: &shape.RefName{
					Name:          "Price",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Price",
				Type: &shape.RefName{
					Name:          "Price",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Quantity",
				Type: &shape.RefName{
					Name:          "Quantity",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Quantity",
				Type: &shape.RefName{
					Name:          "Quantity",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
			{
				Name: "Ctx",
				Type: &shape.RefName{
					Name:          "Context",
					PkgName:       "context",
					PkgImportName: "context",
				},
			},
			{
				Name: "Quantity",
				Type: &shape.RefName{
					Name:          "Quantity",
					PkgName:       "state",
					PkgImportName: "github.com/widmogrod/mkunion/example/state",
				},
			},
		},
	}
}
