stateDiagram
	OrderCancelled: *state.OrderCancelled
	OrderCompleted: *state.OrderCompleted
	OrderError: *state.OrderError
	OrderPending: *state.OrderPending
	OrderProcessing: *state.OrderProcessing

	OrderProcessing --> OrderCancelled: *state.CancelOrderCMD
	[*] --> OrderPending: *state.CreateOrderCMD
	OrderPending --> OrderProcessing: *state.MarkAsProcessingCMD
	OrderProcessing --> OrderCompleted: *state.MarkOrderCompleteCMD
	OrderProcessing --> OrderError: *state.MarkOrderCompleteCMD
	OrderError --> OrderCompleted: *state.TryRecoverErrorCMD
