stateDiagram
	state_OrderCancelled: *state.OrderCancelled
	state_OrderCompleted: *state.OrderCompleted
	state_OrderError: *state.OrderError
	state_OrderPending: *state.OrderPending
	state_OrderProcessing: *state.OrderProcessing

	%% error=cannot cancel order, order must be processing to cancel it; invalid transition 
	state_OrderCancelled --> state_OrderCancelled: ❌*state.CancelOrderCMD
	%% error=cannot cancel order, order must be processing to cancel it; invalid transition 
	state_OrderCompleted --> state_OrderCompleted: ❌*state.CancelOrderCMD
	%% error=cannot cancel order, order must be processing to cancel it; invalid transition 
	state_OrderError --> state_OrderError: ❌*state.CancelOrderCMD
	%% error=cannot cancel order, order must be processing to cancel it; invalid transition 
	state_OrderPending --> state_OrderPending: ❌*state.CancelOrderCMD
	state_OrderProcessing --> state_OrderCancelled: *state.CancelOrderCMD
	%% error=cannot cancel order, order must be processing to cancel it; invalid transition 
	[*] --> [*]: ❌*state.CancelOrderCMD
	%% error=cannot attemp order creation, order exists: invalid transition 
	state_OrderCancelled --> state_OrderCancelled: ❌*state.CreateOrderCMD
	%% error=cannot attemp order creation, order exists: invalid transition 
	state_OrderCompleted --> state_OrderCompleted: ❌*state.CreateOrderCMD
	%% error=cannot attemp order creation, order exists: invalid transition 
	state_OrderError --> state_OrderError: ❌*state.CreateOrderCMD
	%% error=cannot attemp order creation, order exists: invalid transition 
	state_OrderPending --> state_OrderPending: ❌*state.CreateOrderCMD
	%% error=cannot attemp order creation, order exists: invalid transition 
	state_OrderProcessing --> state_OrderProcessing: ❌*state.CreateOrderCMD
	[*] --> state_OrderPending: *state.CreateOrderCMD
	%% error=invalid transition 
	state_OrderCancelled --> state_OrderCancelled: ❌*state.MarkAsProcessingCMD
	%% error=invalid transition 
	state_OrderCompleted --> state_OrderCompleted: ❌*state.MarkAsProcessingCMD
	%% error=invalid transition 
	state_OrderError --> state_OrderError: ❌*state.MarkAsProcessingCMD
	state_OrderPending --> state_OrderProcessing: *state.MarkAsProcessingCMD
	%% error=invalid transition 
	state_OrderProcessing --> state_OrderProcessing: ❌*state.MarkAsProcessingCMD
	%% error=invalid transition 
	[*] --> [*]: ❌*state.MarkAsProcessingCMD
	%% error=cannot mark order as complete, order is not being process; invalid transition 
	state_OrderCancelled --> state_OrderCancelled: ❌*state.MarkOrderCompleteCMD
	%% error=cannot mark order as complete, order is not being process; invalid transition 
	state_OrderCompleted --> state_OrderCompleted: ❌*state.MarkOrderCompleteCMD
	%% error=cannot mark order as complete, order is not being process; invalid transition 
	state_OrderError --> state_OrderError: ❌*state.MarkOrderCompleteCMD
	%% error=cannot mark order as complete, order is not being process; invalid transition 
	state_OrderPending --> state_OrderPending: ❌*state.MarkOrderCompleteCMD
	state_OrderProcessing --> state_OrderCompleted: *state.MarkOrderCompleteCMD
	state_OrderProcessing --> state_OrderError: *state.MarkOrderCompleteCMD
	%% error=cannot self approve order; validation failed 
	state_OrderProcessing --> state_OrderProcessing: ❌*state.MarkOrderCompleteCMD
	%% error=cannot mark order as complete, order is not being process; invalid transition 
	[*] --> [*]: ❌*state.MarkOrderCompleteCMD
	%% error=cannot recover from non error state; invalid transition 
	state_OrderCancelled --> state_OrderCancelled: ❌*state.TryRecoverErrorCMD
	%% error=cannot recover from non error state; invalid transition 
	state_OrderCompleted --> state_OrderCompleted: ❌*state.TryRecoverErrorCMD
	state_OrderError --> state_OrderCompleted: *state.TryRecoverErrorCMD
	%% error=cannot recover from non error state; invalid transition 
	state_OrderPending --> state_OrderPending: ❌*state.TryRecoverErrorCMD
	%% error=cannot recover from non error state; invalid transition 
	state_OrderProcessing --> state_OrderProcessing: ❌*state.TryRecoverErrorCMD
	%% error=cannot recover from non error state; invalid transition 
	[*] --> [*]: ❌*state.TryRecoverErrorCMD
