stateDiagram
	state_OrderCancelled: *state.OrderCancelled
	state_OrderCompleted: *state.OrderCompleted
	state_OrderError: *state.OrderError
	state_OrderPending: *state.OrderPending
	state_OrderProcessing: *state.OrderProcessing

	state_OrderProcessing --> state_OrderCancelled: *state.CancelOrderCMD
	[*] --> state_OrderPending: *state.CreateOrderCMD
	state_OrderPending --> state_OrderProcessing: *state.MarkAsProcessingCMD
	state_OrderProcessing --> state_OrderCompleted: *state.MarkOrderCompleteCMD
	state_OrderProcessing --> state_OrderError: *state.MarkOrderCompleteCMD
	state_OrderError --> state_OrderCompleted: *state.TryRecoverErrorCMD
