stateDiagram
	[*] --> "*state.Candidate": "*state.CreateCandidateCMD"
 %% error=state is not candidate, state: *state.Canonical; invalid cmds 
 %% error=state is not candidate, state: <nil>; invalid cmds 
 %% error=candidate already created, state: *state.Canonical; invalid cmds 
 %% error=candidate already created, state: *state.Candidate; invalid cmds 
	"*state.Candidate" --> "*state.Unique": "*state.MarkAsUniqueCMD"
 %% error=candidate already created, state: *state.Unique; invalid cmds 
 %% error=state is not candidate, state: *state.Unique; invalid cmds 
 %% error=candidate already created, state: *state.Duplicate; invalid cmds 
	"*state.Candidate" --> "*state.Canonical": "*state.MarkAsCanonicalCMD"
 %% error=state is not candidate, state: *state.Unique; invalid cmds 
 %% error=state is not candidate, state: *state.Unique; invalid cmds 
 %% error=state is not candidate, state: *state.Canonical; invalid cmds 
 %% error=state is not candidate, state: *state.Canonical; invalid cmds 
 %% error=state is not candidate, state: *state.Duplicate; invalid cmds 
 %% error=state is not candidate, state: <nil>; invalid cmds 
 %% error=state is not candidate, state: <nil>; invalid cmds 
 %% error=state is not candidate, state: *state.Duplicate; invalid cmds 
	"*state.Candidate" --> "*state.Duplicate": "*state.MarkAsDuplicateCMD"
 %% error=state is not candidate, state: *state.Duplicate; invalid cmds 
