// Code generated by mkunion. DO NOT EDIT.
package main

import (
	"github.com/widmogrod/mkunion/x/shape"
	"github.com/widmogrod/mkunion/x/shared"
)

func init() {
	// Package tags embedded at compile time
	shared.PackageTagsStore("github.com/widmogrod/mkunion/example/runtime_package_tags", map[string]interface{}{
		"author":  shape.Tag{Value: "mkunion development team", Options: nil},
		"license": shape.Tag{Value: "MIT", Options: nil},
		"module":  shape.Tag{Value: "runtime-tags-example", Options: nil},
		"version": shape.Tag{Value: "2.0.0", Options: []string{"stable", "production"}},
	})
	shared.TypeRegistryStore[Completed]("github.com/widmogrod/mkunion/example/runtime_package_tags.Completed")
	shared.TypeRegistryStore[Failed]("github.com/widmogrod/mkunion/example/runtime_package_tags.Failed")
	shared.TypeRegistryStore[Pending]("github.com/widmogrod/mkunion/example/runtime_package_tags.Pending")
	shared.TypeRegistryStore[Running]("github.com/widmogrod/mkunion/example/runtime_package_tags.Running")
}
