// Code generated by mkunion. DO NOT EDIT.
package machine

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(MachineShape())
}

//shape:shape
func MachineShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Machine",
		PkgName:       "machine",
		PkgImportName: "github.com/widmogrod/mkunion/x/machine",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "D",
				Type: &shape.Any{},
			},
			shape.TypeParam{
				Name: "C",
				Type: &shape.Any{},
			},
			shape.TypeParam{
				Name: "S",
				Type: &shape.Any{},
			},
		},
	}
}
