// Code generated by mkunion. DO NOT EDIT.
package machine

import (
	"github.com/widmogrod/mkunion/x/shared"
	"testing"
)

func init() {
	shared.TypeRegistryStore[Case[any, string, int]]("github.com/widmogrod/mkunion/x/machine.Case[any,string,int]")
	shared.TypeRegistryStore[Machine[any, string, int]]("github.com/widmogrod/mkunion/x/machine.Machine[any,string,int]")
	shared.TypeRegistryStore[testing.T]("testing.T")
}
