// Code generated by mkunion. DO NOT EDIT.
package spec

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(CapabilitiesShape())
	shape.Register(DataShape())
	shape.Register(RepoShape())
}

//shape:shape
func CapabilitiesShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Capabilities",
		PkgName:       "spec",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/spec",
		Fields: []*shape.FieldLike{
			{
				Name: "SortByDataField",
				Type: &shape.PrimitiveLike{Kind: &shape.BooleanLike{}},
			},
			{
				Name: "BackwardPagination",
				Type: &shape.PrimitiveLike{Kind: &shape.BooleanLike{}},
			},
			{
				Name: "AtomicBatch",
				Type: &shape.PrimitiveLike{Kind: &shape.BooleanLike{}},
			},
		},
	}
}

//shape:shape
func DataShape() shape.Shape {
	return &shape.AliasLike{
		Name:          "Data",
		PkgName:       "spec",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/spec",
		IsAlias:       true,
		Type: &shape.RefName{
			Name:          "ExampleRecord",
			PkgName:       "schemaless",
			PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless",
		},
	}
}

//shape:shape
func RepoShape() shape.Shape {
	return &shape.AliasLike{
		Name:          "Repo",
		PkgName:       "spec",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/spec",
		IsAlias:       true,
		Type: &shape.RefName{
			Name:          "Repository",
			PkgName:       "schemaless",
			PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless",
			Indexed: []shape.Shape{
				&shape.RefName{
					Name:          "Data",
					PkgName:       "spec",
					PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/spec",
				},
			},
		},
	}
}
