// Code generated by mkunion. DO NOT EDIT.
package effect

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(wideShape())
}

//shape:shape
func wideShape() shape.Shape {
	return &shape.StructLike{
		Name:          "wide",
		PkgName:       "effect",
		PkgImportName: "github.com/widmogrod/mkunion/x/effect",
		Fields: []*shape.FieldLike{
			{
				Name: "Small",
				Type: &shape.PointerLike{
					Type: &shape.Any{},
				},
			},
			{
				Name: "Other",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
		},
	}
}
