// Code generated by mkunion. DO NOT EDIT.
package effect

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(UnitShape())
}

//shape:shape
func UnitShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Unit",
		PkgName:       "effect",
		PkgImportName: "github.com/widmogrod/mkunion/x/effect",
	}
}
