// Code generated by mkunion. DO NOT EDIT.
package query

import (
	"github.com/widmogrod/mkunion/x/shared"
)

func init() {
	shared.TypeRegistryStore[CountUsers]("github.com/widmogrod/mkunion/example/query.CountUsers")
	shared.TypeRegistryStore[DeleteUser]("github.com/widmogrod/mkunion/example/query.DeleteUser")
	shared.TypeRegistryStore[FindUsers]("github.com/widmogrod/mkunion/example/query.FindUsers")
	shared.TypeRegistryStore[GetUser]("github.com/widmogrod/mkunion/example/query.GetUser")
	shared.TypeRegistryStore[InMemory]("github.com/widmogrod/mkunion/example/query.InMemory")
	shared.TypeRegistryStore[User]("github.com/widmogrod/mkunion/example/query.User")
}
