// Code generated by mkunion. DO NOT EDIT.
package projection

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(RecoveryOptionsShape())
}

//shape:shape
func RecoveryOptionsShape() shape.Shape {
	return &shape.StructLike{
		Name:          "RecoveryOptions",
		PkgName:       "projection",
		PkgImportName: "github.com/widmogrod/mkunion/x/projection",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "A",
				Type: &shape.RefName{
					Name:          "SnapshotState",
					PkgName:       "projection",
					PkgImportName: "",
				},
			},
		},
	}
}
