stateDiagram
	traffic_GreenLight: *traffic.GreenLight
	traffic_RedLight: *traffic.RedLight
	traffic_YellowLight: *traffic.YellowLight

	traffic_GreenLight --> traffic_YellowLight: *traffic.NextCMD
	traffic_RedLight --> traffic_GreenLight: *traffic.NextCMD
	traffic_YellowLight --> traffic_RedLight: *traffic.NextCMD
	[*] --> traffic_GreenLight: *traffic.NextCMD
