// Code generated by mkunion. DO NOT EDIT.
package traffic

import (
	"github.com/widmogrod/mkunion/x/machine"
	"github.com/widmogrod/mkunion/x/shared"
	"testing"
)

func init() {
	shared.TypeRegistryStore[machine.Case[Dependencies, TrafficCommand, TrafficState]]("github.com/widmogrod/mkunion/x/machine.Case[github.com/widmogrod/mkunion/example/traffic.Dependencies,github.com/widmogrod/mkunion/example/traffic.TrafficCommand,github.com/widmogrod/mkunion/example/traffic.TrafficState]")
	shared.TypeRegistryStore[machine.Machine[Dependencies, TrafficCommand, TrafficState]]("github.com/widmogrod/mkunion/x/machine.Machine[github.com/widmogrod/mkunion/example/traffic.Dependencies,github.com/widmogrod/mkunion/example/traffic.TrafficCommand,github.com/widmogrod/mkunion/example/traffic.TrafficState]")
	shared.TypeRegistryStore[testing.T]("testing.T")
	shared.TypeRegistryStore[GreenLight]("github.com/widmogrod/mkunion/example/traffic.GreenLight")
	shared.TypeRegistryStore[NextCMD]("github.com/widmogrod/mkunion/example/traffic.NextCMD")
	shared.TypeRegistryStore[RedLight]("github.com/widmogrod/mkunion/example/traffic.RedLight")
	shared.TypeRegistryStore[YellowLight]("github.com/widmogrod/mkunion/example/traffic.YellowLight")
}
