// Code generated by mkunion. DO NOT EDIT.
package generators

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(MkMatchGeneratorShape())
}

//shape:shape
func MkMatchGeneratorShape() shape.Shape {
	return &shape.StructLike{
		Name:          "MkMatchGenerator",
		PkgName:       "generators",
		PkgImportName: "github.com/widmogrod/mkunion/x/generators",
		Fields: []*shape.FieldLike{
			{
				Name: "Header",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
			{
				Name: "PackageName",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
			{
				Name: "MatchSpecs",
				Type: &shape.ListLike{
					Element: &shape.PointerLike{
						Type: &shape.RefName{
							Name:          "MatchSpec",
							PkgName:       "generators",
							PkgImportName: "github.com/widmogrod/mkunion/x/generators",
						},
					},
				},
			},
		},
	}
}
