package generators

import (
	log "github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/widmogrod/mkunion/x/shape"
	"testing"
)

func TestDefaultReductionGenerator(t *testing.T) {
	log.SetLevel(log.DebugLevel)
	inferred, err := shape.InferFromFile("testutils/tree.go")
	assert.NoError(t, err)

	g := NewReducerDefaultReductionGenerator(
		inferred.RetrieveUnion("Tree"),
		NewHelper(WithPackageName("testutils")),
	)

	result, err := g.Generate()
	assert.NoError(t, err)
	assert.Equal(t, `// Code generated by mkunion. DO NOT EDIT.
package testutils

var _ TreeReducer[any] = (*TreeDefaultReduction[any])(nil)

type (
	TreeDefaultReduction[A any] struct {
		PanicOnFallback bool
		DefaultStopReduction bool
		OnBranch func(x *Branch, agg A) (result A, stop bool)
		OnLeaf func(x *Leaf, agg A) (result A, stop bool)
		OnK func(x *K, agg A) (result A, stop bool)
	}
)

func (t *TreeDefaultReduction[A]) ReduceBranch(x *Branch, agg A) (result A, stop bool) {
	if t.OnBranch != nil {
		return t.OnBranch(x, agg)
	}
	if t.PanicOnFallback {
		panic("no fallback allowed on undefined ReduceBranch")
	}
	return agg, t.DefaultStopReduction
}

func (t *TreeDefaultReduction[A]) ReduceLeaf(x *Leaf, agg A) (result A, stop bool) {
	if t.OnLeaf != nil {
		return t.OnLeaf(x, agg)
	}
	if t.PanicOnFallback {
		panic("no fallback allowed on undefined ReduceLeaf")
	}
	return agg, t.DefaultStopReduction
}

func (t *TreeDefaultReduction[A]) ReduceK(x *K, agg A) (result A, stop bool) {
	if t.OnK != nil {
		return t.OnK(x, agg)
	}
	if t.PanicOnFallback {
		panic("no fallback allowed on undefined ReduceK")
	}
	return agg, t.DefaultStopReduction
}
`, string(result))
}
