stateDiagram
	"*workflow.Await" --> "*workflow.Done": "*workflow.Callback"
	"*workflow.ScheduleStopped" --> "*workflow.Scheduled": "*workflow.ResumeSchedule"
	"*workflow.Scheduled" --> "*workflow.Done": "*workflow.Run"
	[*] --> "*workflow.Await": "*workflow.Run"
	[*] --> "*workflow.Done": "*workflow.Run"
	[*] --> "*workflow.Error": "*workflow.Run"
	[*] --> "*workflow.Scheduled": "*workflow.Run"
	"*workflow.Scheduled" --> "*workflow.ScheduleStopped": "*workflow.StopSchedule"
	"*workflow.Error" --> "*workflow.Done": "*workflow.TryRecover"
	"*workflow.Error" --> "*workflow.Error": "*workflow.TryRecover"
