stateDiagram
	[*] --> "*workflow.Done": "*workflow.Run"
	[*] --> "*workflow.Await": "*workflow.Run"
	"*workflow.Await" --> "*workflow.Done": "*workflow.Callback"
 %% error=callback not match 
	[*] --> "*workflow.Error": "*workflow.Run"
 %% error=failed to find workflow hello_world_flow_non_existing: flow hello_world_flow_non_existing not found 
	"*workflow.Error" --> "*workflow.Error": "*workflow.TryRecover"
 %% error=already started 
 %% error=invalid state transition 
 %% error=cannot apply commands, when workflow is completed 
 %% error=cannot apply commands, when workflow is completed 
 %% error=already started 
 %% error=invalid state transition 
 %% error=invalid state transition 
	"*workflow.Error" --> "*workflow.Done": "*workflow.TryRecover"
 %% error=invalid state transition 
 %% error=cannot apply commands, when workflow is completed 
