stateDiagram
	workflow_Await: *workflow.Await
	workflow_Done: *workflow.Done
	workflow_Error: *workflow.Error
	workflow_ScheduleStopped: *workflow.ScheduleStopped
	workflow_Scheduled: *workflow.Scheduled

	workflow_Await --> workflow_Done: *workflow.Callback
	workflow_Await --> workflow_Error: *workflow.ExpireAsync
	workflow_ScheduleStopped --> workflow_Scheduled: *workflow.ResumeSchedule
	workflow_Scheduled --> workflow_Done: *workflow.Run
	[*] --> workflow_Await: *workflow.Run
	[*] --> workflow_Done: *workflow.Run
	[*] --> workflow_Error: *workflow.Run
	[*] --> workflow_Scheduled: *workflow.Run
	workflow_Scheduled --> workflow_ScheduleStopped: *workflow.StopSchedule
	workflow_Error --> workflow_Done: *workflow.TryRecover
	workflow_Error --> workflow_Error: *workflow.TryRecover
