// Code generated by mkunion. DO NOT EDIT.
package workflow

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(DIShape())
}

//shape:shape
func DIShape() shape.Shape {
	return &shape.StructLike{
		Name:          "DI",
		PkgName:       "workflow",
		PkgImportName: "github.com/widmogrod/mkunion/x/workflow",
		Fields: []*shape.FieldLike{
			{
				Name: "FindFunctionF",
				Type: &shape.Any{},
			},
			{
				Name: "FindWorkflowF",
				Type: &shape.Any{},
			},
			{
				Name: "GenerateCallbackIDF",
				Type: &shape.Any{},
			},
			{
				Name: "GenerateRunIDF",
				Type: &shape.Any{},
			},
			{
				Name: "DefaultMaxRetries",
				Type: &shape.PrimitiveLike{
					Kind: &shape.NumberLike{
						Kind: &shape.Int64{},
					},
				},
			},
			{
				Name: "MockTimeNow",
				Type: &shape.PointerLike{
					Type: &shape.RefName{
						Name:          "Time",
						PkgName:       "time",
						PkgImportName: "time",
					},
				},
			},
		},
	}
}
