// Code generated by mkunion. DO NOT EDIT.
package shape

import (
	"github.com/widmogrod/mkunion/x/schema"
)

func init() {
	schema.RegisterUnionTypes(GuardSchemaDef())
}

func GuardSchemaDef() *schema.UnionVariants[Guard] {
	return schema.MustDefineUnion[Guard](
		&Regexp{},
		&Between{},
		&AndGuard{},
		&OrGuard{},
	)
}
