package shape

import (
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

func TestTypeScriptSchemaGeneration(t *testing.T) {

	tsr := NewTypeScriptRenderer()
	tsr.AddUnion(&UnionLike{
		Name:          "Tree",
		PkgName:       "test",
		PkgImportName: "go.import.test",
		Variant: []Shape{
			&StructLike{
				Name:          "Branch",
				PkgName:       "test",
				PkgImportName: "go.import.test",
				Fields: []*FieldLike{
					{
						Name: "L",
						Type: &RefName{
							Name:          "Tree",
							PkgName:       "test",
							PkgImportName: "go.import.test",
						},
					},
					{
						Name: "R",
						Type: &RefName{
							Name:          "Tree",
							PkgName:       "test",
							PkgImportName: "go.import.test",
						},
					},
				},
			},
			&StructLike{
				Name:          "Leaf",
				PkgName:       "test",
				PkgImportName: "go.import.test",
				Fields: []*FieldLike{
					{
						Name: "Value",
						Type: &RefName{
							Name:          "Schema",
							PkgName:       "schema",
							PkgImportName: "github.com/widmogrod/mkunion/x/schema",
						},
					},
				},
			},
		},
	})

	tsr.AddStruct(&StructLike{
		Name:          "SomeStruct",
		PkgName:       "test",
		PkgImportName: "go.import.test",
		Fields:        nil,
	})

	err := tsr.WriteToDir("_test/")
	assert.NoError(t, err)

	assert.FileExists(t, "_test/go_import_test.ts")

	contents, err := os.ReadFile("_test/go_import_test.ts")
	assert.NoError(t, err)

	expected := `//generated by mkunion
export type Tree = {
	// $type this is optional field, that is used to enable discriminative switch-statement in TypeScript, its not part of mkunion schema
	"$type"?: "test.Branch",
	"test.Branch": Branch
} | {
	// $type this is optional field, that is used to enable discriminative switch-statement in TypeScript, its not part of mkunion schema
	"$type"?: "test.Leaf",
	"test.Leaf": Leaf
}

export type Branch = {
	L?: Tree,
	R?: Tree,
}

export type Leaf = {
	Value?: schema.Schema,
}

export type SomeStruct = {
}

//eslint-disable-next-line
import * as schema from './github_com_widmogrod_mkunion_x_schema'
`
	assert.Equal(t, expected, string(contents))
}
