package shape

import (
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

func TestTypeScriptSchemaGeneration(t *testing.T) {
	inferred, err := InferFromFile("testasset/type_example.go")
	if err != nil {
		t.Fatal(err)
	}

	tsr := NewTypeScriptRenderer()
	tsr.AddShape(inferred.RetrieveUnion("Example"))
	tsr.AddShape(inferred.RetrieveStruct("ListOf2"))
	tsr.AddShape(&StructLike{
		Name:          "SomeStruct",
		PkgName:       "test",
		PkgImportName: "go.import.test",
		Fields:        nil,
	})

	err = tsr.WriteToDir("_test/")
	assert.NoError(t, err)

	assert.FileExists(t, "_test/github_com_widmogrod_mkunion_x_shape_testasset.ts")

	contents, err := os.ReadFile("_test/github_com_widmogrod_mkunion_x_shape_testasset.ts")
	assert.NoError(t, err)

	expected := `//generated by mkunion
export type Example = {
	"$type"?: "testasset.A",
	"testasset.A": A
} | {
	"$type"?: "testasset.B",
	"testasset.B": B
} | {
	"$type"?: "testasset.C",
	"testasset.C": C
} | {
	"$type"?: "testasset.D",
	"testasset.D": D
} | {
	"$type"?: "testasset.E",
	"testasset.E": E
} | {
	"$type"?: "testasset.F",
	"testasset.F": F
} | {
	"$type"?: "testasset.H",
	"testasset.H": H
} | {
	"$type"?: "testasset.I",
	"testasset.I": I
} | {
	"$type"?: "testasset.J",
	"testasset.J": J
} | {
	"$type"?: "testasset.K",
	"testasset.K": K
} | {
	"$type"?: "testasset.L",
	"testasset.L": L
} | {
	"$type"?: "testasset.M",
	"testasset.M": M
} | {
	"$type"?: "testasset.N",
	"testasset.N": N
} | {
	"$type"?: "testasset.O",
	"testasset.O": O
} | {
	"$type"?: "testasset.P",
	"testasset.P": P
}

export type A = {
	Name?: string,
}

export type B = {
	Age?: number,
	A?: A,
	T?: time.Time,
}

export type C = string

export type D = number

export type E = number

export type F = boolean

export type H = {[key: string]: Example}

export type I = Example[]

export type J = string[]

export type K = A

export type L = List

export type M = List

export type N = time.Duration

export type O = ListOf<time.Duration>

export type P = ListOf2<ListOf<any>, ListOf2<number, time.Duration>>

export type ListOf2<T1, T2> = {}

//eslint-disable-next-line
import * as time from './time'
`
	assert.Equal(t, expected, string(contents))
}
