// Code generated by mkunion. DO NOT EDIT.
package taskqueue

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(QueueShape())
}

//shape:shape
func QueueShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Queue",
		PkgName:       "taskqueue",
		PkgImportName: "github.com/widmogrod/mkunion/x/taskqueue",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "T",
				Type: &shape.Any{},
			},
		},
	}
}
