// Code generated by mkunion. DO NOT EDIT.
package typedful

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(UserShape())
	shape.Register(UsersCountByAgeShape())
}

//shape:shape
func UserShape() shape.Shape {
	return &shape.StructLike{
		Name:          "User",
		PkgName:       "typedful",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/typedful",
		Fields: []*shape.FieldLike{
			{
				Name: "Name",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
			{
				Name: "Age",
				Type: &shape.PrimitiveLike{
					Kind: &shape.NumberLike{
						Kind: &shape.Int{},
					},
				},
			},
		},
	}
}

//shape:shape
func UsersCountByAgeShape() shape.Shape {
	return &shape.StructLike{
		Name:          "UsersCountByAge",
		PkgName:       "typedful",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/typedful",
		Fields: []*shape.FieldLike{
			{
				Name: "Count",
				Type: &shape.PrimitiveLike{
					Kind: &shape.NumberLike{
						Kind: &shape.Int{},
					},
				},
			},
		},
	}
}
