// Code generated by mkunion. DO NOT EDIT.
package typedful

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(TypedAppendLogShape())
}

//shape:shape
func TypedAppendLogShape() shape.Shape {
	return &shape.StructLike{
		Name:          "TypedAppendLog",
		PkgName:       "typedful",
		PkgImportName: "github.com/widmogrod/mkunion/x/storage/schemaless/typedful",
		TypeParams: []shape.TypeParam{
			shape.TypeParam{
				Name: "T",
				Type: &shape.Any{},
			},
		},
	}
}
