name: docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # generate the code, so docs have all files necessary to link to
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.21
        id: go

      - run: cd cmd/mkunion; go get -v -t -d ./...
      - run: cd cmd/mkunion; go build -o mkunion

      - run: go install github.com/matryer/moq@latest

      - run: go get -v -t -d ./...

      # generate code with mkunion
      - run: ./cmd/mkunion/mkunion watch -g ./...
      # generate code with go generate
      - run: go generate ./...

      # generate documentation
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force