// Code generated by mkunion. DO NOT EDIT.
package billing

import (
	"github.com/widmogrod/mkunion/x/shape"
)

func init() {
	shape.Register(ChargeErrorShape())
	shape.Register(ChargeShape())
	shape.Register(EffectShape())
	shape.Register(InvalidAmountShape())
	shape.Register(OutOfCreditsShape())
	shape.Register(OutcomeShape())
	shape.Register(QuotaExceededShape())
	shape.Register(RateLimitedShape())
	shape.Register(ReceiptShape())
	shape.Register(RefusedShape())
}

//shape:shape

func ChargeErrorShape() shape.Shape {
	return &shape.UnionLike{
		Name:          "ChargeError",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Variant: []shape.Shape{
			InvalidAmountShape(),
			RateLimitedShape(),
			QuotaExceededShape(),
			OutOfCreditsShape(),
		},
	}
}

func InvalidAmountShape() shape.Shape {
	return &shape.StructLike{
		Name:          "InvalidAmount",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "Reason",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "ChargeError",
			},
		},
	}
}

func RateLimitedShape() shape.Shape {
	return &shape.StructLike{
		Name:          "RateLimited",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "RetryAfter",
				Type: &shape.RefName{
					Name:          "Duration",
					PkgName:       "time",
					PkgImportName: "time",
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "ChargeError",
			},
		},
	}
}

func QuotaExceededShape() shape.Shape {
	return &shape.StructLike{
		Name:          "QuotaExceeded",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "ResetAt",
				Type: &shape.RefName{
					Name:          "Time",
					PkgName:       "time",
					PkgImportName: "time",
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "ChargeError",
			},
		},
	}
}

func OutOfCreditsShape() shape.Shape {
	return &shape.StructLike{
		Name:          "OutOfCredits",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "Missing",
				Type: &shape.PrimitiveLike{
					Kind: &shape.NumberLike{
						Kind: &shape.Int{},
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "ChargeError",
			},
		},
	}
}

//shape:shape

func EffectShape() shape.Shape {
	return &shape.UnionLike{
		Name:          "Effect",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Variant: []shape.Shape{
			ChargeShape(),
		},
	}
}

func ChargeShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Charge",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "Returns",
				Type: &shape.RefName{
					Name:          "Returns",
					PkgName:       "f",
					PkgImportName: "github.com/widmogrod/mkunion/f",
					Indexed: []shape.Shape{
						&shape.RefName{
							Name:          "Outcome",
							PkgName:       "billing",
							PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
						},
					},
				},
			},
			{
				Name: "Amount",
				Type: &shape.PrimitiveLike{
					Kind: &shape.NumberLike{
						Kind: &shape.Int{},
					},
				},
			},
		},
		Tags: map[string]shape.Tag{
			"mkunion": {
				Value: "Effect",
			},
		},
	}
}

//shape:shape
func OutcomeShape() shape.Shape {
	return &shape.AliasLike{
		Name:          "Outcome",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		IsAlias:       true,
		Type: &shape.RefName{
			Name:          "Result",
			PkgName:       "f",
			PkgImportName: "github.com/widmogrod/mkunion/f",
			Indexed: []shape.Shape{
				&shape.RefName{
					Name:          "Receipt",
					PkgName:       "billing",
					PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
				},
				&shape.RefName{
					Name:          "ChargeError",
					PkgName:       "billing",
					PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
				},
			},
		},
	}
}

//shape:shape
func ReceiptShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Receipt",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "ID",
				Type: &shape.PrimitiveLike{Kind: &shape.StringLike{}},
			},
		},
	}
}

//shape:shape
func RefusedShape() shape.Shape {
	return &shape.StructLike{
		Name:          "Refused",
		PkgName:       "billing",
		PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
		Fields: []*shape.FieldLike{
			{
				Name: "Reason",
				Type: &shape.RefName{
					Name:          "ChargeError",
					PkgName:       "billing",
					PkgImportName: "github.com/widmogrod/mkunion/example/compose/billing",
				},
			},
		},
	}
}
