// Code generated by mkunion. DO NOT EDIT.
package billing

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/widmogrod/mkunion/x/shared"
	"time"
)

type ChargeErrorVisitor interface {
	VisitInvalidAmount(v *InvalidAmount) any
	VisitRateLimited(v *RateLimited) any
	VisitQuotaExceeded(v *QuotaExceeded) any
	VisitOutOfCredits(v *OutOfCredits) any
}

type ChargeError interface {
	AcceptChargeError(g ChargeErrorVisitor) any
}

var (
	_ ChargeError = (*InvalidAmount)(nil)
	_ ChargeError = (*RateLimited)(nil)
	_ ChargeError = (*QuotaExceeded)(nil)
	_ ChargeError = (*OutOfCredits)(nil)
)

func (r *InvalidAmount) AcceptChargeError(v ChargeErrorVisitor) any { return v.VisitInvalidAmount(r) }
func (r *RateLimited) AcceptChargeError(v ChargeErrorVisitor) any   { return v.VisitRateLimited(r) }
func (r *QuotaExceeded) AcceptChargeError(v ChargeErrorVisitor) any { return v.VisitQuotaExceeded(r) }
func (r *OutOfCredits) AcceptChargeError(v ChargeErrorVisitor) any  { return v.VisitOutOfCredits(r) }

func MatchChargeErrorR3[T0, T1, T2 any](
	x ChargeError,
	f1 func(x *InvalidAmount) (T0, T1, T2),
	f2 func(x *RateLimited) (T0, T1, T2),
	f3 func(x *QuotaExceeded) (T0, T1, T2),
	f4 func(x *OutOfCredits) (T0, T1, T2),
) (T0, T1, T2) {
	switch v := x.(type) {
	case *InvalidAmount:
		return f1(v)
	case *RateLimited:
		return f2(v)
	case *QuotaExceeded:
		return f3(v)
	case *OutOfCredits:
		return f4(v)
	}
	var result1 T0
	var result2 T1
	var result3 T2
	return result1, result2, result3
}

func MatchChargeErrorR2[T0, T1 any](
	x ChargeError,
	f1 func(x *InvalidAmount) (T0, T1),
	f2 func(x *RateLimited) (T0, T1),
	f3 func(x *QuotaExceeded) (T0, T1),
	f4 func(x *OutOfCredits) (T0, T1),
) (T0, T1) {
	switch v := x.(type) {
	case *InvalidAmount:
		return f1(v)
	case *RateLimited:
		return f2(v)
	case *QuotaExceeded:
		return f3(v)
	case *OutOfCredits:
		return f4(v)
	}
	var result1 T0
	var result2 T1
	return result1, result2
}

func MatchChargeErrorR1[T0 any](
	x ChargeError,
	f1 func(x *InvalidAmount) T0,
	f2 func(x *RateLimited) T0,
	f3 func(x *QuotaExceeded) T0,
	f4 func(x *OutOfCredits) T0,
) T0 {
	switch v := x.(type) {
	case *InvalidAmount:
		return f1(v)
	case *RateLimited:
		return f2(v)
	case *QuotaExceeded:
		return f3(v)
	case *OutOfCredits:
		return f4(v)
	}
	var result1 T0
	return result1
}

func MatchChargeErrorR0(
	x ChargeError,
	f1 func(x *InvalidAmount),
	f2 func(x *RateLimited),
	f3 func(x *QuotaExceeded),
	f4 func(x *OutOfCredits),
) {
	switch v := x.(type) {
	case *InvalidAmount:
		f1(v)
	case *RateLimited:
		f2(v)
	case *QuotaExceeded:
		f3(v)
	case *OutOfCredits:
		f4(v)
	}
}
func init() {
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.ChargeError", ChargeErrorFromJSON, ChargeErrorToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.InvalidAmount", InvalidAmountFromJSON, InvalidAmountToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.OutOfCredits", OutOfCreditsFromJSON, OutOfCreditsToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.QuotaExceeded", QuotaExceededFromJSON, QuotaExceededToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.RateLimited", RateLimitedFromJSON, RateLimitedToJSON)
}

type ChargeErrorUnionJSON struct {
	Type          string          `json:"$type,omitempty"`
	InvalidAmount json.RawMessage `json:"billing.InvalidAmount,omitempty"`
	RateLimited   json.RawMessage `json:"billing.RateLimited,omitempty"`
	QuotaExceeded json.RawMessage `json:"billing.QuotaExceeded,omitempty"`
	OutOfCredits  json.RawMessage `json:"billing.OutOfCredits,omitempty"`
}

func ChargeErrorFromJSON(x []byte) (ChargeError, error) {
	if x == nil || len(x) == 0 {
		return nil, nil
	}
	if string(x[:4]) == "null" {
		return nil, nil
	}
	var data ChargeErrorUnionJSON
	err := json.Unmarshal(x, &data)
	if err != nil {
		return nil, fmt.Errorf("billing.ChargeErrorFromJSON: %w", err)
	}

	switch data.Type {
	case "billing.InvalidAmount":
		return InvalidAmountFromJSON(data.InvalidAmount)
	case "billing.RateLimited":
		return RateLimitedFromJSON(data.RateLimited)
	case "billing.QuotaExceeded":
		return QuotaExceededFromJSON(data.QuotaExceeded)
	case "billing.OutOfCredits":
		return OutOfCreditsFromJSON(data.OutOfCredits)
	}

	if data.InvalidAmount != nil {
		return InvalidAmountFromJSON(data.InvalidAmount)
	} else if data.RateLimited != nil {
		return RateLimitedFromJSON(data.RateLimited)
	} else if data.QuotaExceeded != nil {
		return QuotaExceededFromJSON(data.QuotaExceeded)
	} else if data.OutOfCredits != nil {
		return OutOfCreditsFromJSON(data.OutOfCredits)
	}
	return nil, fmt.Errorf("billing.ChargeErrorFromJSON: unknown type: %s", data.Type)
}

func ChargeErrorToJSON(x ChargeError) ([]byte, error) {
	if x == nil {
		return []byte(`null`), nil
	}
	return MatchChargeErrorR2(
		x,
		func(y *InvalidAmount) ([]byte, error) {
			body, err := InvalidAmountToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("billing.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:          "billing.InvalidAmount",
				InvalidAmount: body,
			})
		},
		func(y *RateLimited) ([]byte, error) {
			body, err := RateLimitedToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("billing.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:        "billing.RateLimited",
				RateLimited: body,
			})
		},
		func(y *QuotaExceeded) ([]byte, error) {
			body, err := QuotaExceededToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("billing.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:          "billing.QuotaExceeded",
				QuotaExceeded: body,
			})
		},
		func(y *OutOfCredits) ([]byte, error) {
			body, err := OutOfCreditsToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("billing.ChargeErrorToJSON: %w", err)
			}
			return json.Marshal(ChargeErrorUnionJSON{
				Type:         "billing.OutOfCredits",
				OutOfCredits: body,
			})
		},
	)
}

func InvalidAmountFromJSON(x []byte) (*InvalidAmount, error) {
	result := new(InvalidAmount)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("billing.InvalidAmountFromJSON: %w", err)
	}
	return result, nil
}

func InvalidAmountToJSON(x *InvalidAmount) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*InvalidAmount)(nil)
	_ json.Marshaler   = (*InvalidAmount)(nil)
)

func (r *InvalidAmount) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONInvalidAmount(*r)
}
func (r *InvalidAmount) _marshalJSONInvalidAmount(x InvalidAmount) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldReason []byte
	fieldReason, err = r._marshalJSONstring(x.Reason)
	if err != nil {
		return nil, fmt.Errorf("billing: InvalidAmount._marshalJSONInvalidAmount: field name Reason; %w", err)
	}
	if len(fieldReason) == 0 {
		fieldReason = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Reason\":")
	buf.Write(fieldReason)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *InvalidAmount) _marshalJSONstring(x string) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("billing: InvalidAmount._marshalJSONstring:; %w", err)
	}
	return result, nil
}
func (r *InvalidAmount) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONInvalidAmount(data)
	if err != nil {
		return fmt.Errorf("billing: InvalidAmount.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *InvalidAmount) _unmarshalJSONInvalidAmount(data []byte) (InvalidAmount, error) {
	result := InvalidAmount{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("billing: InvalidAmount._unmarshalJSONInvalidAmount: native struct unwrap; %w", err)
	}
	if fieldReason, ok := partial["Reason"]; ok {
		result.Reason, err = r._unmarshalJSONstring(fieldReason)
		if err != nil {
			return result, fmt.Errorf("billing: InvalidAmount._unmarshalJSONInvalidAmount: field Reason; %w", err)
		}
	}
	return result, nil
}
func (r *InvalidAmount) _unmarshalJSONstring(data []byte) (string, error) {
	var result string
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("billing: InvalidAmount._unmarshalJSONstring: native primitive unwrap; %w", err)
	}
	return result, nil
}

func RateLimitedFromJSON(x []byte) (*RateLimited, error) {
	result := new(RateLimited)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("billing.RateLimitedFromJSON: %w", err)
	}
	return result, nil
}

func RateLimitedToJSON(x *RateLimited) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*RateLimited)(nil)
	_ json.Marshaler   = (*RateLimited)(nil)
)

func (r *RateLimited) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONRateLimited(*r)
}
func (r *RateLimited) _marshalJSONRateLimited(x RateLimited) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldRetryAfter []byte
	fieldRetryAfter, err = r._marshalJSONtime_Duration(x.RetryAfter)
	if err != nil {
		return nil, fmt.Errorf("billing: RateLimited._marshalJSONRateLimited: field name RetryAfter; %w", err)
	}
	if len(fieldRetryAfter) == 0 {
		fieldRetryAfter = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"RetryAfter\":")
	buf.Write(fieldRetryAfter)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *RateLimited) _marshalJSONtime_Duration(x time.Duration) ([]byte, error) {
	result, err := shared.JSONMarshal[time.Duration](x)
	if err != nil {
		return nil, fmt.Errorf("billing: RateLimited._marshalJSONtime_Duration:; %w", err)
	}
	return result, nil
}
func (r *RateLimited) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONRateLimited(data)
	if err != nil {
		return fmt.Errorf("billing: RateLimited.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *RateLimited) _unmarshalJSONRateLimited(data []byte) (RateLimited, error) {
	result := RateLimited{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("billing: RateLimited._unmarshalJSONRateLimited: native struct unwrap; %w", err)
	}
	if fieldRetryAfter, ok := partial["RetryAfter"]; ok {
		result.RetryAfter, err = r._unmarshalJSONtime_Duration(fieldRetryAfter)
		if err != nil {
			return result, fmt.Errorf("billing: RateLimited._unmarshalJSONRateLimited: field RetryAfter; %w", err)
		}
	}
	return result, nil
}
func (r *RateLimited) _unmarshalJSONtime_Duration(data []byte) (time.Duration, error) {
	result, err := shared.JSONUnmarshal[time.Duration](data)
	if err != nil {
		return result, fmt.Errorf("billing: RateLimited._unmarshalJSONtime_Duration: native ref unwrap; %w", err)
	}
	return result, nil
}

func QuotaExceededFromJSON(x []byte) (*QuotaExceeded, error) {
	result := new(QuotaExceeded)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("billing.QuotaExceededFromJSON: %w", err)
	}
	return result, nil
}

func QuotaExceededToJSON(x *QuotaExceeded) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*QuotaExceeded)(nil)
	_ json.Marshaler   = (*QuotaExceeded)(nil)
)

func (r *QuotaExceeded) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONQuotaExceeded(*r)
}
func (r *QuotaExceeded) _marshalJSONQuotaExceeded(x QuotaExceeded) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldResetAt []byte
	fieldResetAt, err = r._marshalJSONtime_Time(x.ResetAt)
	if err != nil {
		return nil, fmt.Errorf("billing: QuotaExceeded._marshalJSONQuotaExceeded: field name ResetAt; %w", err)
	}
	if len(fieldResetAt) == 0 {
		fieldResetAt = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"ResetAt\":")
	buf.Write(fieldResetAt)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *QuotaExceeded) _marshalJSONtime_Time(x time.Time) ([]byte, error) {
	result, err := shared.JSONMarshal[time.Time](x)
	if err != nil {
		return nil, fmt.Errorf("billing: QuotaExceeded._marshalJSONtime_Time:; %w", err)
	}
	return result, nil
}
func (r *QuotaExceeded) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONQuotaExceeded(data)
	if err != nil {
		return fmt.Errorf("billing: QuotaExceeded.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *QuotaExceeded) _unmarshalJSONQuotaExceeded(data []byte) (QuotaExceeded, error) {
	result := QuotaExceeded{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("billing: QuotaExceeded._unmarshalJSONQuotaExceeded: native struct unwrap; %w", err)
	}
	if fieldResetAt, ok := partial["ResetAt"]; ok {
		result.ResetAt, err = r._unmarshalJSONtime_Time(fieldResetAt)
		if err != nil {
			return result, fmt.Errorf("billing: QuotaExceeded._unmarshalJSONQuotaExceeded: field ResetAt; %w", err)
		}
	}
	return result, nil
}
func (r *QuotaExceeded) _unmarshalJSONtime_Time(data []byte) (time.Time, error) {
	result, err := shared.JSONUnmarshal[time.Time](data)
	if err != nil {
		return result, fmt.Errorf("billing: QuotaExceeded._unmarshalJSONtime_Time: native ref unwrap; %w", err)
	}
	return result, nil
}

func OutOfCreditsFromJSON(x []byte) (*OutOfCredits, error) {
	result := new(OutOfCredits)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("billing.OutOfCreditsFromJSON: %w", err)
	}
	return result, nil
}

func OutOfCreditsToJSON(x *OutOfCredits) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*OutOfCredits)(nil)
	_ json.Marshaler   = (*OutOfCredits)(nil)
)

func (r *OutOfCredits) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONOutOfCredits(*r)
}
func (r *OutOfCredits) _marshalJSONOutOfCredits(x OutOfCredits) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldMissing []byte
	fieldMissing, err = r._marshalJSONint(x.Missing)
	if err != nil {
		return nil, fmt.Errorf("billing: OutOfCredits._marshalJSONOutOfCredits: field name Missing; %w", err)
	}
	if len(fieldMissing) == 0 {
		fieldMissing = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Missing\":")
	buf.Write(fieldMissing)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *OutOfCredits) _marshalJSONint(x int) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("billing: OutOfCredits._marshalJSONint:; %w", err)
	}
	return result, nil
}
func (r *OutOfCredits) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONOutOfCredits(data)
	if err != nil {
		return fmt.Errorf("billing: OutOfCredits.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *OutOfCredits) _unmarshalJSONOutOfCredits(data []byte) (OutOfCredits, error) {
	result := OutOfCredits{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("billing: OutOfCredits._unmarshalJSONOutOfCredits: native struct unwrap; %w", err)
	}
	if fieldMissing, ok := partial["Missing"]; ok {
		result.Missing, err = r._unmarshalJSONint(fieldMissing)
		if err != nil {
			return result, fmt.Errorf("billing: OutOfCredits._unmarshalJSONOutOfCredits: field Missing; %w", err)
		}
	}
	return result, nil
}
func (r *OutOfCredits) _unmarshalJSONint(data []byte) (int, error) {
	var result int
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("billing: OutOfCredits._unmarshalJSONint: native primitive unwrap; %w", err)
	}
	return result, nil
}

type EffectVisitor interface {
	VisitCharge(v *Charge) any
}

type Effect interface {
	AcceptEffect(g EffectVisitor) any
}

var (
	_ Effect = (*Charge)(nil)
)

func (r *Charge) AcceptEffect(v EffectVisitor) any { return v.VisitCharge(r) }

func MatchEffectR3[T0, T1, T2 any](
	x Effect,
	f1 func(x *Charge) (T0, T1, T2),
) (T0, T1, T2) {
	switch v := x.(type) {
	case *Charge:
		return f1(v)
	}
	var result1 T0
	var result2 T1
	var result3 T2
	return result1, result2, result3
}

func MatchEffectR2[T0, T1 any](
	x Effect,
	f1 func(x *Charge) (T0, T1),
) (T0, T1) {
	switch v := x.(type) {
	case *Charge:
		return f1(v)
	}
	var result1 T0
	var result2 T1
	return result1, result2
}

func MatchEffectR1[T0 any](
	x Effect,
	f1 func(x *Charge) T0,
) T0 {
	switch v := x.(type) {
	case *Charge:
		return f1(v)
	}
	var result1 T0
	return result1
}

func MatchEffectR0(
	x Effect,
	f1 func(x *Charge),
) {
	switch v := x.(type) {
	case *Charge:
		f1(v)
	}
}

// EffectHandler answers every Effect with the type it declares in f.Returns.
// Adding a variant to Effect breaks every EffectHandler at compile time.
type EffectHandler interface {
	HandleCharge(ctx context.Context, op *Charge) (Outcome, error)
}

// EffectOf is a Effect that answers with R.
type EffectOf[R any] interface {
	Effect
	HandleEffect(ctx context.Context, h EffectHandler) (R, error)
}

var (
	_ EffectOf[Outcome] = (*Charge)(nil)
)

func (r *Charge) HandleEffect(ctx context.Context, h EffectHandler) (Outcome, error) {
	return h.HandleCharge(ctx, r)
}

// Perform and Answer let a variant be performed by any handler value that has
// this union's Handle methods, so operations from several unions can share one
// program and one handler (see x/effect: Op, OpOf, Fx). Answer keeps the type.
func (r *Charge) Answer(ctx context.Context, h any) (Outcome, error) {
	typed, ok := h.(EffectHandler)
	if !ok {
		var zero Outcome
		return zero, fmt.Errorf("billing: handler %T does not implement EffectHandler", h)
	}
	return typed.HandleCharge(ctx, r)
}

func (r *Charge) Perform(ctx context.Context, h any) (any, error) { return r.Answer(ctx, h) }

// EffectHandlerFunc adapts a typed EffectHandler to a plain function over the union.
// The answer is the type the variant declares; only its static type is lost.
func EffectHandlerFunc(h EffectHandler) func(ctx context.Context, op Effect) (any, error) {
	return func(ctx context.Context, op Effect) (any, error) {
		return MatchEffectR2(op,
			func(x *Charge) (any, error) { return x.HandleEffect(ctx, h) },
		)
	}
}

// EffectDefaults answers every Effect with the zero value of its declared type.
// Embed it in a handler and override only the methods you care about.
type EffectDefaults struct{}

var _ EffectHandler = EffectDefaults{}

func (EffectDefaults) HandleCharge(context.Context, *Charge) (Outcome, error) {
	var zero Outcome
	return zero, nil
}

// EffectFuncs is a EffectHandler made of functions, one per operation, for handlers
// written inline. A nil function answers with the zero value of its declared type.
type EffectFuncs struct {
	Charge func(ctx context.Context, op *Charge) (Outcome, error)
}

var _ EffectHandler = EffectFuncs{}

func (fs EffectFuncs) HandleCharge(ctx context.Context, op *Charge) (Outcome, error) {
	if fs.Charge == nil {
		var zero Outcome
		return zero, nil
	}
	return fs.Charge(ctx, op)
}

func init() {
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.Charge", ChargeFromJSON, ChargeToJSON)
	shared.JSONMarshallerRegister("github.com/widmogrod/mkunion/example/compose/billing.Effect", EffectFromJSON, EffectToJSON)
}

type EffectUnionJSON struct {
	Type   string          `json:"$type,omitempty"`
	Charge json.RawMessage `json:"billing.Charge,omitempty"`
}

func EffectFromJSON(x []byte) (Effect, error) {
	if x == nil || len(x) == 0 {
		return nil, nil
	}
	if string(x[:4]) == "null" {
		return nil, nil
	}
	var data EffectUnionJSON
	err := json.Unmarshal(x, &data)
	if err != nil {
		return nil, fmt.Errorf("billing.EffectFromJSON: %w", err)
	}

	switch data.Type {
	case "billing.Charge":
		return ChargeFromJSON(data.Charge)
	}

	if data.Charge != nil {
		return ChargeFromJSON(data.Charge)
	}
	return nil, fmt.Errorf("billing.EffectFromJSON: unknown type: %s", data.Type)
}

func EffectToJSON(x Effect) ([]byte, error) {
	if x == nil {
		return []byte(`null`), nil
	}
	return MatchEffectR2(
		x,
		func(y *Charge) ([]byte, error) {
			body, err := ChargeToJSON(y)
			if err != nil {
				return nil, fmt.Errorf("billing.EffectToJSON: %w", err)
			}
			return json.Marshal(EffectUnionJSON{
				Type:   "billing.Charge",
				Charge: body,
			})
		},
	)
}

func ChargeFromJSON(x []byte) (*Charge, error) {
	result := new(Charge)
	err := result.UnmarshalJSON(x)
	if err != nil {
		return nil, fmt.Errorf("billing.ChargeFromJSON: %w", err)
	}
	return result, nil
}

func ChargeToJSON(x *Charge) ([]byte, error) {
	return x.MarshalJSON()
}

var (
	_ json.Unmarshaler = (*Charge)(nil)
	_ json.Marshaler   = (*Charge)(nil)
)

func (r *Charge) MarshalJSON() ([]byte, error) {
	if r == nil {
		return nil, nil
	}
	return r._marshalJSONCharge(*r)
}
func (r *Charge) _marshalJSONCharge(x Charge) ([]byte, error) {
	buf := bytes.Buffer{}
	buf.WriteByte('{')
	var err error
	var fieldAmount []byte
	fieldAmount, err = r._marshalJSONint(x.Amount)
	if err != nil {
		return nil, fmt.Errorf("billing: Charge._marshalJSONCharge: field name Amount; %w", err)
	}
	if len(fieldAmount) == 0 {
		fieldAmount = []byte("null")
	}
	if buf.Len() > 1 {
		buf.WriteByte(',')
	}
	buf.WriteString("\"Amount\":")
	buf.Write(fieldAmount)
	buf.WriteByte('}')
	return buf.Bytes(), nil
}
func (r *Charge) _marshalJSONint(x int) ([]byte, error) {
	result, err := json.Marshal(x)
	if err != nil {
		return nil, fmt.Errorf("billing: Charge._marshalJSONint:; %w", err)
	}
	return result, nil
}
func (r *Charge) UnmarshalJSON(data []byte) error {
	result, err := r._unmarshalJSONCharge(data)
	if err != nil {
		return fmt.Errorf("billing: Charge.UnmarshalJSON: %w", err)
	}
	*r = result
	return nil
}
func (r *Charge) _unmarshalJSONCharge(data []byte) (Charge, error) {
	result := Charge{}
	var partial map[string]json.RawMessage
	err := json.Unmarshal(data, &partial)
	if err != nil {
		return result, fmt.Errorf("billing: Charge._unmarshalJSONCharge: native struct unwrap; %w", err)
	}
	if fieldAmount, ok := partial["Amount"]; ok {
		result.Amount, err = r._unmarshalJSONint(fieldAmount)
		if err != nil {
			return result, fmt.Errorf("billing: Charge._unmarshalJSONCharge: field Amount; %w", err)
		}
	}
	return result, nil
}
func (r *Charge) _unmarshalJSONint(data []byte) (int, error) {
	var result int
	err := json.Unmarshal(data, &result)
	if err != nil {
		return result, fmt.Errorf("billing: Charge._unmarshalJSONint: native primitive unwrap; %w", err)
	}
	return result, nil
}
